lalrpop/lalrpop

- lalrpop/src/build/filetext.rs
If pos was greater than the position of the last newline in the file, then the filter would return an empty set and unwrap would fail.
> Fixed line_col failing for positions on the last line

- lalrpop-snap/src/build/mod.rs
This gets past the error reported in https://github.com/nikomatsakis/lalrpop/issues/18, though I see further parser failures in the calculator example.
> Fix build script error handling on windows

- lalrpop-snap/src/build/mod.rs
I noticed (due to long build times) that on windows the rebuild checker was always returning true.
I discovered in this thread that windows does support file modification times: https://www.reddit.com/r/rust/comments/3dhxxv/metadata_modified/
Looking in my local documentation I found the `last_write_time()` so I added a windows specific check.
> Add file time checking for windows (re)builds

- lalrpop/Cargo.toml
- lalrpop/src/lib.rs
The rand crate pulls in a lot of dependencies which many users of
lalrpop probably wouldn't otherwise require. It is enough to require it
to run the tests, which means using lalrpop doesn't require this
anymore.
This will come to full fruition eventually when a new lalrpop snapshot
is created, until then rand will still be pulled in.
> Drop rand from required dependencies

- lalrpop-test/src/issue_55.lalrpop
- lalrpop-test/src/main.rs
- lalrpop/src/normalize/inline/mod.rs
- lalrpop/src/normalize/inline/test.rs
Fix inlining so that different appearances of the same symbol can be inlined in multiple ways.
Fixes #55.
> Fix inlining when inlined symbol appears multiple times in one production

- lalrpop/src/build/mod.rs
See [#53](https://github.com/nikomatsakis/lalrpop/issues/53)
After a normal `cargo build` using LALRPOP 0.9.0, the generated rust file is set as read-only. Subsequent calls to `cargo build` fail, but if I manually remove the read-only attribute on the file, the build succeeds.
This patch unsets read-only on the generated rust file before attempting to remove it and generate a new one. It still sets read-only after the file has been generated in an attempt to preserve the external semantics of the build.
This appears to consistently resolve my build issues on Windows. I have not and cannot test it on any other platforms.
> Unset read only on generated rust file before removing it to fix build failure on Windows

- RELEASES.md
- lalrpop/src/collections/map.rs
- lalrpop/src/collections/mod.rs
- lalrpop/src/collections/multimap.rs
- lalrpop/src/collections/set.rs
- lalrpop/src/grammar/repr.rs
- lalrpop/src/kernel_set.rs
- lalrpop/src/lexer/dfa/mod.rs
- lalrpop/src/lexer/dfa/overlap.rs
- lalrpop/src/lib.rs
- lalrpop/src/log.rs
- lalrpop/src/lr1/ascent.rs
- lalrpop/src/lr1/build/mod.rs
- lalrpop/src/lr1/build_lalr/mod.rs
- lalrpop/src/lr1/core/mod.rs
- lalrpop/src/lr1/error/mod.rs
- lalrpop/src/lr1/first/mod.rs
- lalrpop/src/lr1/trace/mod.rs
- lalrpop/src/lr1/trace/trace_graph/mod.rs
- lalrpop/src/normalize/inline/graph/mod.rs
- lalrpop/src/normalize/lower/mod.rs
- lalrpop/src/normalize/mod.rs
- lalrpop/src/normalize/prevalidate/mod.rs
- lalrpop/src/normalize/resolve/mod.rs
- lalrpop/src/normalize/token_check/mod.rs
- lalrpop/src/util.rs
There is plenty of work left to do on improving the LR(1) construction code, but I just picked some low-hanging fruit. Instead of computing the transitive closure after analyzing the shift items, and using the TC to index the state, I now index the state just by the "kernel" set, which is the items that resulted after shifting, before we add the epsilon moves. I believe this is equivalent. The result is that we compute the TC once per state and not once per transition. This makes a MASSIVE difference for large grammars.
Here are some timing results from [rustypop](https://github.com/nikomatsakis/rustypop). Before:
```
Mr-Darcy-2. time ~/versioned/lalrpop/lalrpop/target/release/lalrpop -f parser-lalr.lalrpop
processing file `parser-lalr.lalrpop`
real    2m51.857s
user    2m51.462s
sys …
```
> Make LR(1) less naive

- lalrpop/src/lr1/error/mod.rs
LALROP -> LALRPOP
PS: The GitHub online editor is great for tiny fixes like this!
> Fix typo in report_error_suggest_inline

- lalrpop/src/lexer/dfa/overlap.rs
add_range() uses the wrong index into the vector of disjoint ranges, which causes panics for some grammars and might produce faulty parsers for others. Try this:
```
grammar;
A = r"[0-1]";
B = r"[0-2]";
C = r"[0-3]";
```
With the current master I get this panic when trying to generate a parser:
> error: failed to run custom build command for `comatus v0.1.0 (file:///home/ll/src/git/comatus)`
> Process didn't exit successfully: `/home/ll/src/git/comatus/target/debug/build/comatus-b2d8aadff4832138/build-script-build` (exit code: 101)
> --- stdout
> processing file `/home/ll/src/git/comatus/src/aaaa.lalrpop`
> 
> --- stderr
> thread '<main>' panicked at 'assertion failed: low_range.is_disjoint(max_range)', /home/ll/.cargo/git/checkouts/lalrpop-c0dd81ff2de87ac9/4893ddacc6743849a9249b5a7579e92d …
> Fix panicking bug in add_range().

- lalrpop/src/build/action.rs
- lalrpop/src/build/mod.rs
- lalrpop/src/lexer/intern_token/mod.rs
- lalrpop/src/lr1/ascent.rs
- lalrpop/src/rust/mod.rs
This makes it so that `lalrpop` doesn't emit top-level module-level attributes. It does so by:
* Moving the `#[allow(unused_variables)]` to each use-site.
* Using fully qualified paths instead of `#[allow(unused_imports)]`.
This has the additional advantage that the user will get warnings for unused manual imports.
The main purpose of this pull request is however to allow generated parser files to be `include!()`d.
> Don't emit module-level attributes

- doc/tutorial.md
- lalrpop/src/lr1/codegen/parse_table.rs
Since error recovery requires cloneable tokens we avoid emitting the error recovery code unless it is actually needed. Note that this change still keeps the error terminal in the generated tables.
> Only generate code for error recovery if it is used

- README.md
Very minor contribution, however this fixes a 404 in the README.md.
> Fixes typo in README.md for Configuration object

- lalrpop-test/src/main.rs
- lalrpop/src/lr1/codegen/ascent.rs
- lalrpop/src/lr1/codegen/parse_table.rs
This just adds the terminal strings defined in the grammar which is not the best possible information but it is better than no information.
Partial fix for #58
> feat: Add the expected successor tokens to UnrecognizedToken errors

- .gitignore
- lalrpop-test/src/error_recovery_pull_182.lalrpop
- lalrpop-test/src/main.rs
- lalrpop/src/lr1/codegen/parse_table.rs
This caused panics in certain error recovery scenarios as a reduce action represented by a negative number would get casted to `usize` which then caused an index out of bounds panic.
The added tests were extracted and minimized from [gluon's grammar](https://github.com/gluon-lang/gluon/blob/abd06a4f6efa24d5dc4800373f6dfbc066dd661d/parser/src/grammar.lalrpop) with the test case below being a minimal reproduction.
Panicking
```
type Test = a ->
```
Valid expression
```
type Test = a -> a
in 1
```
> fix: Don't accidentally cast a reduce action to usize

- lalrpop-test/src/expr.lalrpop
- lalrpop-test/src/expr_lalr.lalrpop
- lalrpop-test/src/sub_ascent.lalrpop
- lalrpop-test/src/util/tok.rs
- lalrpop/src/lr1/codegen/parse_table.rs
> parse table generator is now packing terminal parameters into tuple

- lalrpop-intern/src/lib.rs
- lalrpop/src/api/mod.rs
- lalrpop/src/build/mod.rs
- lalrpop/src/grammar/parse_tree.rs
- lalrpop/src/lr1/core/mod.rs
- lalrpop/src/lr1/mod.rs
- lalrpop/src/lr1/report/mod.rs
- lalrpop/src/main.rs
- lalrpop/src/session.rs
Currently lalrpop is able to produce very nice high-level errors. They are very useful especially when someone is interested in assistance with resolving conflicts. I believe that I am not only one user who would prefer to have also a brief summary of produced automaton and encountered conflicts. After many years of using bison and menhir I am used to have such summary and solve conflicts using mainly such brief report.
In future we could include a high-level description of conflicts in report file as additional section.
Usage
---------
If lalrpop is executed with `--report` option, then report will be generated for each input file. The report is written in file with `.report` extension in same directory where `.rs` file has been generated.
Example
------------ …
> Report generation

- lalrpop/src/build/action.rs
- lalrpop/src/lr1/codegen/ascent.rs
- lalrpop/src/rust/mod.rs
Generated recursive ascent parser contains public functions
for every state and every action.
Only the top level state function(s) must be public.
> Make action and state functions private.

- .gitignore
- lalrpop-snap/src/lexer/intern_token/mod.rs
- lalrpop-test/src/error_issue_113.lalrpop
- lalrpop-test/src/main.rs
- lalrpop/src/lexer/intern_token/mod.rs
This allows custom error types to be used as User ParseError
This should fix #113
> Add user uses in generated mod intern_token

- .travis.yml
- lalrpop-test/src/main.rs
- lalrpop/src/lr1/lane_table/construct/merge.rs
- lalrpop/src/lr1/lane_table/construct/mod.rs
Lalrpop 0.13 regressed in Rust compatibility; 0.12.5 compiled fine on Rust 1.13 onwards, but 0.13 required at least Rust 1.16.
With a few small adjustments, Rust 1.13 compatibility can be restored.
It might also be a good idea to put the minimal supported Rust version in the CI configuration. That way breaking changes can be detected. If the advantages of using a newer Rust version outweigh breaking compatibility, then requiring a newer Rust version is fine, but at least breakages are explicit in this way, and they can be mentioned in the changelog.
> Restore Rust 1.13 compatibility

- doc/calculator/src/calculator2.lalrpop
- doc/tutorial.md
- lalrpop-test/src/expr_arena.lalrpop
- lalrpop-test/src/expr_arena_ast.rs
- lalrpop-test/src/main.rs
- lalrpop/src/normalize/lower/mod.rs
- lalrpop/src/normalize/norm_util.rs
- lalrpop/src/normalize/prevalidate/mod.rs
- lalrpop/src/normalize/prevalidate/test.rs
Solution to #226.
Lalrpop validates also usage of the `<>` expression with struct constructors -- it requires to assign field names to values.
* Example
```
pub Foo: Foo = {
<Num> Num <Num> => Foo{<>}
};
```
Provokes error message:
```
wieczyk-> lalrpop -f src/example.lalrpop 
processing file `src/example.lalrpop`
src/example.lalrpop:7:5: 8:0 error: the `<>` expression requires to explicitly assign fields' names to values
~~~~~~~~~~~~~~~~~~~~~~~~~~~+
|     <Num> Num <Num> => Foo{<>} |
| };
+~
```
> Issue226 ltgt construct should work with named input

- doc/pascal/lalrpop/Cargo.toml
- lalrpop-snap/Cargo.toml
rustc-serialize is deprecated and is not actually used in lalrpop
right now anyway.
> Remove dependencies on rustc-serialize.

- lalrpop/src/build/mod.rs
This will at least print an error message with the location, rather than
panicking, which is a lot more user-friendly :)
r? @nikomatsakis
> Ignore the possible expected token when we find an unrecognized token

- lalrpop/src/lr1/error/mod.rs
- lalrpop/src/lr1/error/test.rs
- lalrpop/src/lr1/lane_table/construct/mod.rs
- lalrpop/src/lr1/lane_table/table/mod.rs
We still don't get optimal results here, but that's a separate issue.
Fixes #249.
> avoid out-of-bounds error in error classification

- lalrpop-test/src/main.rs
- lalrpop-test/src/where_clause_with_forall.lalrpop
- lalrpop-test/src/where_clause_with_forall.rs
- lalrpop/src/grammar/parse_tree.rs
- lalrpop/src/grammar/repr.rs
- lalrpop/src/normalize/lower/mod.rs
- lalrpop/src/parser/lrgrammar.lalrpop
- lalrpop/src/parser/mod.rs
- lalrpop/src/parser/test.rs
- lalrpop/src/tok/mod.rs
- lalrpop/src/tok/test.rs
This will make #247 easier to implement, so we can determine which type parameters are referenced in which where clauses.
r? @nikomatsakis
> Create an explicit structure for `where` clauses

- doc/tutorial.md
It translated `<e:T?>` into `e?`, when it should've been `T?`.
`<e:T?>` is a nonterminal bound to the name, `T?` is a nonterminal bound to no name, and `e?` is meaningless.
> Fix the "no-brackets" example code

- doc/calculator/src/calculator6.lalrpop
- lalrpop-test/src/error_recovery.lalrpop
- lalrpop-test/src/error_recovery_pull_182.lalrpop
- lalrpop-test/src/expr_module_attributes.lalrpop
- lalrpop-test/src/main.rs
- lalrpop-test/src/util/mod.rs
- lalrpop-util/src/lib.rs
- lalrpop/src/build/mod.rs
- lalrpop/src/grammar/pattern.rs
- lalrpop/src/grammar/repr.rs
- lalrpop/src/lexer/intern_token/mod.rs
- lalrpop/src/lr1/codegen/ascent.rs
- lalrpop/src/lr1/codegen/base.rs
- lalrpop/src/normalize/lower/mod.rs
- lalrpop/src/normalize/tyinfer/mod.rs
- lalrpop/src/normalize/tyinfer/test.rs
- lalrpop/src/rust/mod.rs
Because the types `(usize, &str)` and `()` do not implement `fmt::Display`, `lalrpop_util::ParseError<usize, (usize, &str),()>` doesn't either, which is a nuisance when displaying an error message.
I added three methods to ParseError that can be used to transform these types into more convenient types. They are of the form `fn map_loc<F,LL>(self, op: F) -> ParseError<LL, T, E> where F: Fn(L) -> LL`.
One use case is formatting, as above. Another is switching the `usize` byte offset locations into for example line/column numbers.
Although it is less pure, for user convenience it might be a good idea to use `String` rather than `()` as the default user-error type because strings have `fmt::Display`. I have not implemented this. Additionally, it might be an idea to add specific `Display` and …
> Make ParseError Displayable

- .gitignore
- lalrpop-test/src/associated_types.rs
- lalrpop-test/src/error_recovery_issue_240.lalrpop
- lalrpop-test/src/error_recovery_lalr_loop.lalrpop
- lalrpop-test/src/error_recovery_lock_in.lalrpop
- lalrpop-test/src/error_recovery_span.lalrpop
- lalrpop-test/src/main.rs
- lalrpop-test/src/where_clause_with_forall.rs
- lalrpop/src/lr1/codegen/base.rs
- lalrpop/src/lr1/codegen/parse_table.rs
- lalrpop/src/lr1/lane_table/construct/mod.rs
This change reworks LALRPOP's error recovery mechanism:
- Internally, we now generate a function (two, really) that gets invoked, rather than inlining the code twice.
- We now handle LALR and lane-table grammars correctly, in particular accounting for the fact that they can reduce several times before encountering an error (and hence we must trace through reductions when testing if we can recover from a particular state).
- This avoids the infinite loops.
- We now use a modified algorithm that prefers to drop fewer tokens (but may drop more states as a result) -- [see description here](https://github.com/nikomatsakis/lalrpop/issues/240/#issuecomment-338483176).
I am not sure about the final bullet point. At first I thought it was clearly better, but I've become less sure. I'd be curious …
> Rework error recovery mechanism

- .gitignore
- lalrpop-test/src/error_issue_278.lalrpop
- lalrpop-test/src/main.rs
- lalrpop/src/lr1/codegen/parse_table.rs
If some production in the grammar returns an error, give it priority
over built-in errors.
Fixes #278.
> Return grammar errors first

- lalrpop/src/rust/mod.rs
> Add rustfmt_skip attribute.

- .travis.yml
- lalrpop-test/src/expr.lalrpop
- lalrpop/src/build/mod.rs
- lalrpop/src/grammar/parse_tree.rs
- lalrpop/src/grammar/repr.rs
- lalrpop/src/lr1/codegen/base.rs
- lalrpop/src/lr1/codegen/parse_table.rs
- lalrpop/src/lr1/codegen/test_all.rs
- lalrpop/src/normalize/lower/mod.rs
- lalrpop/src/normalize/macro_expand/mod.rs
- lalrpop/src/normalize/prevalidate/mod.rs
- lalrpop/src/parser/lrgrammar.lalrpop
- lalrpop/src/rust/mod.rs
Fixes #256.
This isn't ready yet.
@nikomatsakis Do you know where the `pub use` reexports of `parse_<nonterminal>` happen? I spent a few hours getting to this point, I figure asking might just be easier. :)
> Add support for pub(restricted).

- lalrpop/src/lr1/codegen/parse_table.rs
Part of #304 . We detect how many reductions and states that is needed before generating any code and then use the minimum necessary integer size to hold all of these. Most grammars likely fit within `i16` but smaller ones may fit within `i8`
.
The first commit simplifies the generated code a bit but did not help reduce the binary code in any way. Might make it a bit less work for LLVM at least.
>  perf: Use the minimum integer size necessary to represent states 

- lalrpop/src/tok/mod.rs
- lalrpop/src/tok/test.rs
Fixes #307
When encountering the sequence `'\` only search for the closing `'` after the character following the `\`.
> fix error on parsing a single-quote char literal

- lalrpop/src/collections/map.rs
- lalrpop/src/collections/mod.rs
- lalrpop/src/lr1/codegen/parse_table.rs
This attempts to merge all symbol variants which would contain the same
type into one, letting us reduce the number of `pop_` functions being
generated.
Reduces the number of lines for `lrgrammar.lalrpop` from 67k to 57k
(a reduction of about 15%)
> feat: De-duplicate symbol variants for parse tables

- README.md
Before it would link to the image itself
> docs: Fix the link to travis

- .gitignore
- lalrpop-test/src/error_recovery_type_in_macro.lalrpop
- lalrpop-test/src/lib.rs
- lalrpop/src/grammar/repr.rs
- lalrpop/src/normalize/tyinfer/mod.rs
- lalrpop/src/normalize/tyinfer/test.rs
I had missed updating this place in https://github.com/lalrpop/lalrpop/commit/6bf1c9e940c51ec1a74bbfee3df894b871ea5b01 and it appears this type mismatch only occurs when `!` occurs in macro.
> fix: Use the correct type for `!` in macro expanded productions 

- doc/pascal/lalrpop/build.rs
- lalrpop/src/lexer/intern_token/mod.rs
- lalrpop/src/lr1/codegen/base.rs
- lalrpop/src/lr1/codegen/test_all.rs
- lalrpop/src/rust/mod.rs
Due to https://github.com/rust-lang/rust/issues/18810 (https://github.com/rust-lang/rfcs/issues/752)
it is not possible to have an inner attribute in a file that gets
used with `include!`.
Specifying the attribute on each parser module is less precise and more
duplication but it will at least work for that case. If a user wants to
apply the rustfmt on the whole module they can still add an outer
attribute manually as well.
> fix: Allow lalrpop parsers to be used with include!

- doc/src/tutorial/001_adding_lalrpop.md
Cargo used to require `build = "build.rs"` line but it no longer does. Update accordingly.
> Update tutorial for Cargo build script change

- doc/calculator/src/main.rs
- doc/src/tutorial/002_paren_numbers.md
- doc/src/tutorial/004_controlling_lexer.md
- doc/src/tutorial/006_building_asts.md
- doc/src/tutorial/007_macros.md
- doc/src/tutorial/008_error_recovery.md
I wrote my first proper LALRPOP parser last night (loving the library so far!) and I was slightly tripped up by the fact that [the book](http://lalrpop.github.io/lalrpop/) hadn't been updated to reflect the API changes from the most recent release. I was able to get by, since the code examples in the repo had been updated a while back (#317), but I thought I'd submit a PR to avoid other people running into that confusion 😄 
For the most part, I've just copied and pasted the code samples across from [`main.rs`](https://github.com/17cupsofcoffee/lalrpop/blob/0eb0082a556ed33e653a9e867daf78ce9f0922bc/doc/calculator/src/main.rs) - the only place I had to make changes to the prose was in [the second chapter](https://github.com/17cupsofcoffee/lalrpop/blob/0eb0082a556ed33e653a9e867daf78ce9f0922bc/ …
> Update docs for 0.15

- .gitignore
- lalrpop-test/src/lib.rs
- lalrpop-test/src/match_alternatives.lalrpop
- lalrpop/src/lexer/intern_token/mod.rs
^foo|bar is (^foo)|bar, and not ^(foo|bar). Adding parens should
fix it.
closes #358 
Funny how this is the second time I fix this bug in a parser generator, the fist fix was for fall: https://github.com/matklad/fall/commit/02b7fe1f471aeeb836b414caa3fe8a9235dc131c =P
> Correctly anchor regex at the begining

- RELEASES.md
The X in `parse_X` is not the same X as in `X::new()` -- for example in my code I needed to go from `parse_Expr` to `ExprParser::new()`.
> Clarify 0.15 upgrade instructions

- .travis.yml
- Cargo.lock
- lalrpop-util/src/lib.rs
Seems to be intentional that attributes on the macro invocation does not
work so we instead allow attributes inside it.
https://github.com/rust-lang/rust/issues/28284
> feat: Allow attributes to be specified in lalrpop_mod!

- lalrpop/src/build/mod.rs
- lalrpop/src/parser/lrgrammar.lalrpop
- lalrpop/src/tok/mod.rs
- lalrpop/src/tok/test.rs
The "\\" and "\"" escapes are necessary to make it possible to put arbitrary text in a string literal at all. We have to support "\t" and "\n" to compile the `whitespace` example from the book. But the other Rust escape sequences like "\u{2a}" don't really seem necessary.
Fixes #405.
> Process escape sequences in string literals appearing as terminals.

- lalrpop/src/build/mod.rs
Since `lalrpop` now defaults to outputting files into `$OUT_DIR`, there is not much sense in marking generated files as read-only.  This behavior additionally interferes with `git` and `cargo fix` anyway.
Fixes #426.
> Don't make generated files read-only

- lalrpop/src/api/mod.rs
- lalrpop/src/build/mod.rs
- lalrpop/src/session.rs
Cargo allows build scripts to emit directives to specify their
dependencies, so that modifying other files does not cause them to be
rerun. This adds a configuration option to emit those directives,
defaulting to false to avoid interfering with other parts of the build
script and leading to hard-to-debug issues.
On Windows, some files cannot be represented in the UTF-8 used by Cargo,
and a build warning is emitted instead.
I've tested this change manually, but didn't see an easy way to test
it programmatically as part of the codebase, especially because
`to_string_lossy()` can never return `None` on Unix platforms.
> Support conditional execution by Cargo.

- lalrpop/src/lr1/codegen/parse_table.rs
- lalrpop/src/parser/lrgrammar.rs
In gluon's parser I have a lalrpop symbol type that ends up at 400Kb
which is expensive to copy around. By moving the `push` call into each
reduction instead we make it easier for LLVM to elide memcpys and I
observed a reduction in memcpy uses from 27% to 18% of of the total
parse time.
>  perf: Avoid some memcpying in reductions

- doc/src/tutorial/002_paren_numbers.md
Add the missing link to `main.rs`.
It should be fixed.
> Add a link to `main.rs`

- lalrpop/src/normalize/resolve/mod.rs
Before this patch, I was told:
```
src/cypher.lalrpop:309:37: 309:54 error: `nonterminal` is a AndExpression, not a macro
```
I think it should be the other way around ;-)
> Order of string for error message confusing

- lalrpop/src/normalize/prevalidate/mod.rs
I guess it has been left in there for debugging?
> Remove confusing "ok" message printed to stdout

- lalrpop/src/lexer/intern_token/mod.rs
On Rust 1.33, the current generated code emits a warning because hidden lifetime parameters in types are deprecated. This occurs in the `impl Display for Token`, and happens because `fmt::Formatter` has a lifetime parameter.
This PR adds an explicit lifetime parameter `'f` to the generated code, so it will work on all supported versions of Rust.
> Remove warning about hidden lifetime parameter

- .travis.yml
- lalrpop-test/src/util/mod.rs
- lalrpop/src/test_util.rs
rust-lang/rust/pull/59076 changed the multiline Debug representation to
always include a trailing comma. This change currently breaks our tests
on beta and nightly, since we use this Debug representation to compare
expected parsing output.
We cannot simply add the trailing commas to the expected output strings,
since that would break on older rustc versions we support. Instead, this
commit makes it so that all trailing commas are stripped before the
comparison.
This workaround can be removed once rust-lang/rust/pull/59076 reaches
our minimum supported rustc version.
> Ignore trailing commas in `ExpectedDebug`

- lalrpop/src/lexer/intern_token/mod.rs
- lalrpop/src/lr1/lane_table/test.rs
Now that our minimum supported Rust version is 1.31.0, we can make the switch from `String::trim_left` (deprecated since 1.33.0) to `String::trim_start`.
This also lets us get rid of the `allow(deprecated)` introduced as a workaround for issue #428.
> Replace deprecated `trim_left` with `trim_start`

- lalrpop/src/lexer/intern_token/mod.rs
A very small fix. Thanks for the documentation!
> doc(api) Fix `intern_token` example

- lalrpop-util/src/lib.rs
I just tried to use `lalrpop_util::lalrpop_mod!(pub(crate) grammar)` and got a `no rules expected the token "("` error during macro expansion.
By the looks of it, as well as matching the normal `ident` and `expr` "metavariables", `macro_rules!` macros can use [a `vis` metavariable][1] to match a (possibly empty) visibility specifier like `pub` or `pub(crate)`.
This PR updates the macro definition to use `vis` instead of manually matching on the private and `pub` variants.
[1]: https://doc.rust-lang.org/reference/macros-by-example.html#metavariables
> Update lalrpop_mod!() to match on any $vis pattern

- lalrpop/Cargo.toml
unicode-xid is at version 0.2.0 in debian unstable.  I want to make sure lalrpop can work with it!
This is an aspirational PR -- i want to see what the CI does with it, and i would love to hear feedback from the lalrpop devs about any concerns that they have about this change.
> depend on a more recent version of the unicode-xid crate

- README.md
Solang uses lalrpop for parsing Solidity.
Signed-off-by: Sean Young <sean@mess.org>
> Add Solang to the list of examples

- doc/src/quick_start_guide.md
- doc/src/tutorial/001_adding_lalrpop.md
The v0.2 regex crate came out 3 years ago.
I was about to publish a crate of my own when I saw this pre-1.0 dependency in my `Cargo.toml` that I had copied from the book.
> Update book to regex v1.0

- Cargo.lock
- lalrpop-util/Cargo.toml
- lalrpop-util/src/lexer.rs
- lalrpop-util/src/lib.rs
- lalrpop/Cargo.toml
- lalrpop/src/build/mod.rs
- lalrpop/src/grammar/parse_tree.rs
- lalrpop/src/lexer/intern_token/mod.rs
- lalrpop/src/lr1/codegen/base.rs
- lalrpop/src/normalize/prevalidate/mod.rs
- lalrpop/src/normalize/token_check/mod.rs
Also puts generating a lexer under the `lexer` feature with a helpful
error message instead of implicitly requiring `regex` to be in
`Cargo.toml`
BREAKING CHANGE
Add the `lexer` feature to `lalrpop` if the generated lexer is used
Closes #373
> refactor: Move the generated lexer into lalrpop-util

- lalrpop/src/generate.rs
- lalrpop/src/lr1/codegen/parse_table.rs
- lalrpop/src/parser/lrgrammar.rs
Makes it easier for llvm to inline the pop functions
> perf: Move the symbol mismatch panic into a colder path

- Cargo.lock
- lalrpop-test/src/lib.rs
- lalrpop-test/src/loc_issue_90_lib.rs
- lalrpop-test/src/sp_from_optional.lalrpop
- lalrpop/src/lr1/codegen/ascent.rs
- lalrpop/src/lr1/codegen/parse_table.rs
- lalrpop/src/parser/lrgrammar.rs
Empty non-terminals used to be spanned by the whitespace between the
previous and next token. If the non-terminal was the first thing in
another production this span would leak into that production, causing it
to have a to large span assigned.
This makes empty productions instead only point to the start of the
lookahead to avoid this problem.
> fix: Don't include whitespace in the span with empty nonterminals

- lalrpop-util/src/lib.rs
Useful especially combined with the `?` syntax, as you can do `MyLocalError(...)?` and it gets transformed into a `ParseError` without having to worry about writing out the wrapper.
> Add From<E> for ParseError<L, T, E>

- doc/calculator/src/calculator4.lalrpop
- doc/calculator/src/calculator5.lalrpop
- doc/calculator/src/calculator6.lalrpop
- doc/calculator/src/calculator6b.lalrpop
- doc/calculator/src/calculator7.lalrpop
- doc/calculator/src/calculator8.lalrpop
- doc/calculator/src/calculator9.lalrpop
Refer to https://doc.rust-lang.org/reference/items/use-declarations.html.
In 2018 edition, "crate::" is needed for in-scope items.
I  ran "cargo build" & "cargo test" with 'edition="2018"' in Cargo.toml, build and tests pass.
> Ship calculator .lalrpop files to rust 2018

- .travis.yml
- lalrpop/src/lr1/codegen/parse_table.rs
- lalrpop/src/parser/lrgrammar.rs
Merges the panic from the unwrap into the general symbol mismatch,
hopefully simplifying LLVMs work.
cc #543
> refactor: Avoid generating a panic for unwrapping symbols

- doc/src/tutorial/index.md
Just stumbled upon this. Looks like #522 missed updating these links.
> fix broken links in tutorial

- doc/src/tutorial/004_full_expressions.md
I was getting some dead code warnings I couldn't turn off. @segeljakt pointed out on Gitter that it might be the `pub` annotations. I didn't see anything in the docs that clarified that, so I add some text as early as seemed reasonable.
> Clarify meaning/purpose of `pub` annotations on nonterminals

- lalrpop/src/build/mod.rs
I'm attempting to build the [basic-cookies](https://github.com/drjokepu/basic-cookies) crate using the [Bazel](https://bazel.build/) build system and I ran into an issue where the `.lalrpop` files were not being processed leading to the following error:
```output
error: couldn't read /private/var/tmp/_bazel_user/32618c3132899251ff30687e197d6243/sandbox/darwin-sandbox/1299/execroot/cargo_raze/bazel-out/darwin-fastbuild/bin/external/cargo_raze__basic_cookies__0_1_4/basic_cookies_build_script.out_dir/cookie_grammar.rs: No such file or directory (os error 2)
--> external/cargo_raze__basic_cookies__0_1_4/src/cookie.rs:9:1
|
9 | lalrpop_mod!(cookie_grammar);
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info) …
```
> Fixed inability to process symlinks to lalrpop files

- README.md
According to: https://github.com/gleam-lang/gleam/commit/4fe17ae84159ec01d43e895291e085d5eba3ca6c
> Seems like Gleam doesn't use lalrpop anymore

- Cargo.lock
- lalrpop-util/Cargo.toml
- lalrpop-util/src/lib.rs
- lalrpop-util/src/state_machine.rs
- lalrpop/src/grammar/parse_tree.rs
- lalrpop/src/lr1/codegen/ascent.rs
- lalrpop/src/lr1/codegen/base.rs
- lalrpop/src/lr1/codegen/parse_table.rs
- lalrpop/src/rust/mod.rs
Fixes #397.
I went with an option rather than only using `core`/`alloc` because a) `alloc` still requires `extern crate alloc;` in the root of the crate, and b) `core` isn't available in Rust 2015, which `calculator`, `whitespace` etc are.
Oh, also, I turned off rustfmt since it was reformatting everything; I'm not sure what the formatting guidelines are for lalrpop, or if rustfmt just hasn't been run in a while.
> Allow generating no_std-compatible parsers

- lalrpop/Cargo.toml
0.5.1 seems to not build on Rust stable,
via its transitive bit-vec 0.5.1 dependency.
I upgraded lalrpop recently and bit-set resolved to 0.5.1 for whatever reason, and the build was broken. Updating bit-set to 0.5.2 fixed the problem in my project. This patch should prevent others from running into the same problem.
> Require bit-set 0.5.2 or greater

- doc/src/tutorial/005_building_asts.md
- doc/src/tutorial/008_error_recovery.md
Make the code in the book the same as the `calculator` directory.
Add some explanation about `grammer` in `008_error_recovery.md`.
> Fix outdated code in the lalrpop book

- lalrpop/src/normalize/precedence/mod.rs
- lalrpop/src/normalize/precedence/test.rs
- lalrpop/src/normalize/prevalidate/mod.rs
- lalrpop/src/normalize/prevalidate/test.rs
#555 introduced precedence annotations. However, one practical quirk is that one needs to re-specify the precedence on each alternative. Usually, alternatives are grouped by precedence in a grammar, and we could use one annotation for a whole block.
To illustrate the point, here is the calc example of the LALRPOP book with current precedence annotations:
```
Expr: i32 = {
#[precedence(lvl="0")]
Num,
#[precedence(lvl="0")]
"(" <Expr> ")",
#[precedence(lvl="1")] #[assoc(side="left")]
<l:Expr> "*" <r:Expr> => l * r,
#[precedence(lvl="1")] #[assoc(side="left")]
<l:Expr> "/" <r:Expr> => l / r,
#[precedence(lvl="2")] #[assoc(side="left")]
<l:Expr> "+" <r:Expr> => l + r,
#[precedence(lvl="2")] #[assoc(side="left")]
<l:Expr> "-" <r:Expr> => l - r,
};
```
Which is a bit verbose. Here is how we can …
> Spanned precedence annotations

- lalrpop-test/src/inline_fallible.lalrpop
- lalrpop-test/src/lib.rs
- lalrpop/src/build/action.rs
Fixes #91.  (both bugs mentioned in https://github.com/lalrpop/lalrpop/issues/91#issuecomment-789413948)
#Just2016Things
---
~~**Note:** I believe this may be the first time LALRPOP will ever use the `?` operator in codegen.~~
~~While this certainly is supported by LALRPOP's MSRV of 1.36, theoretically speaking it is still possible for older versions of rust to compile LALRPOP's output files (and so this may technically boost the minimum version of rust required for doing *that*).  That said, it does not change codegen for any existing code that already used to compile.~~
**Edit:** Never mind that.  Minimum required version of Rust to compile the output rust files is *also* 1.36, due to use of the `alloc` crate, so `?` should be fair game.
> Fix inlining of fallible productions

- doc/calculator/src/calculator5.lalrpop
- doc/src/tutorial/006_macros.md
I didn't realise that this feature had been added for a while, so it would be nice if the tutorial used it rather than the old `let mut v = v` approach.
> Use `mut` production variables in tutorial

- lalrpop-test/src/lib.rs
- lalrpop-test/src/use_super_internal_tok.lalrpop
- lalrpop-test/src/util/mod.rs
- lalrpop/src/lexer/intern_token/mod.rs
A one-line change to lalrpop/src/lexer/intern_token/mod.rs.  (the rest is tests)
I was surprised to see that the infrastructure was already there, and in fact the correct function was even already in use! Just this argument was wrong.
I found it surprising that this would be the case, so I did some sleuthing into the commit history. The single line modified by this commit was written in this commit: 1b206d166572d5a76baaa2792
This line was probably copied from [this similar line](https://github.com/lalrpop/lalrpop/blob/fc9986c725d908a60b11d8480711afa33f7f3564/lalrpop/src/build/mod.rs#L338) that I believe generates the 'uses' at the very top of the generated grammar file.
You can see the test added for the aforementioned commit here: …
> Fix #480 ('use super::' with internal lexer)

- doc/src/lexer_tutorial/001_lexer_gen.md
- doc/src/tutorial/001_adding_lalrpop.md
- doc/src/tutorial/002_paren_numbers.md
- doc/src/tutorial/003_type_inference.md
- doc/src/tutorial/004_full_expressions.md
- doc/src/tutorial/005_building_asts.md
- doc/src/tutorial/006_macros.md
- doc/src/tutorial/007_fallible_actions.md
- doc/src/tutorial/009_state_parameter.md
- doc/src/tutorial/index.md
Fix [books](http://lalrpop.github.io/lalrpop/index.html) link.
https://github.com/lalrpop/lalrpop/issues/546
This issue caused by relative path in markdown. Then I changed relative path to absolute path.
And in [tutorial first page](http://lalrpop.github.io/lalrpop/tutorial/index.html), path is changed main.rs → lib.rs.
I would appreciate it is checked.
Fixes #598 #546
> Fix book links (issue #546)

- Cargo.lock
- lalrpop/Cargo.toml
This also upgrades term to 0.7, which switches the unmaintained `dirs` crate out for `dirs-next`.
> Upgrade ascii-canvas to 3.0

- doc/book.toml
Fixes #617 
With this fix, mdBook will generate the line `<base href="/lalrpop/">` instead of `<base href="/">` in the 404.html file.
> Fix LALRPOP book site-url option

- doc/src/lexer_tutorial/001_lexer_gen.md
The previous multiline comments example captures everything between the first `/*` and the last `*/` unless I'm mistaken.
See for example below grammar: It parses `/* */ poc1 /* */ poc2` into `poc2`, but it should be `poc1`. This is fixed with the updated regex (from here: https://stackoverflow.com/a/36328890)
```
grammar();
match {
r"\s*" => { }, // The default whitespace skipping is disabled an `ignore pattern` is specified
r"//[^\n\r]*[\n\r]*" => { }, // Skip `// comments`
r"/\*([^\*]*\*+[^\*/])*([^\*]*\*+|[^\*])*\*/" => { },  // Skip `/* comments */`
_
}
pub Poc: String = {
<Name> => <>,
<Name> Poc => <>,
}
Name: String = r"[A-Za-z_][A-Za-z0-9_]*!?" => (<>).to_owned();
```
> Fix /* */ multiline comment lexer example

- Cargo.lock
- lalrpop/Cargo.toml
This PR updates petgraph to the latest available version, v0.6.0. No code changes were actually required in lalrpop.
> feat: update petgraph to v0.6.0

- lalrpop/src/build/mod.rs
- lalrpop/src/parser/lrgrammar.rs
Was switching from my build script building lalrpop to just verifying that the
generated file is up to date via the sha3 and noticed that the sha3 is
formatted.. very wrong.
> Fix leading zeros in each byte of the sha3 getting dropped

- Cargo.lock
- lalrpop/Cargo.toml
- lalrpop/src/build/mod.rs
- lalrpop/src/lib.rs
This is identical to #695 but the patch is slightly more minimal.
> Replace atty dependency with is-terminal (Fix RUSTSEC-2021-0145)

- doc/src/advanced_setup.md
This fulfills issue #586 and adds a link to the lane table README
for users who are interested in how LALRPOP works.
> document lalr mode in the advanced settings

- lalrpop/src/tok/mod.rs
- lalrpop/src/tok/test.rs
Lex raw identifiers (identifiers prefixed with `r#`). Fixes #613
> Lex raw identifiers

- doc/src/advanced_setup.md
"linking outside the root directory is forbidden"
Fixes https://github.com/lalrpop/lalrpop/issues/713
> fix lane table link

- tools/ci-install.sh
I noticed the `deploy` Github Actions pipeline fails due to a compilation error of mdbook.
I simply upgraded it from 0.4.7 to 0.4.28.
It works on my machine™️
> Upgrade mdbook to 0.4.28

- doc/calculator/src/main.rs
- doc/pascal/lalrpop/src/main.rs
- doc/whitespace/src/lib.rs
- lalrpop-test/src/lib.rs
- lalrpop-test/src/pub_in.rs
> hide clippy warnings from generated sources in tests and docs

- lalrpop-test/Cargo.toml
- lalrpop-test/src/associated_types.lalrpop
- lalrpop-test/src/error.lalrpop
- lalrpop-test/src/error_recovery.lalrpop
- lalrpop-test/src/error_recovery_issue_240.lalrpop
- lalrpop-test/src/error_recovery_lalr_loop.lalrpop
- lalrpop-test/src/error_recovery_lock_in.lalrpop
- lalrpop-test/src/error_recovery_pull_182.lalrpop
- lalrpop-test/src/error_recovery_span.lalrpop
- lalrpop-test/src/error_recovery_type_in_macro.lalrpop
- lalrpop-test/src/expr.lalrpop
- lalrpop-test/src/expr_arena.lalrpop
- lalrpop-test/src/expr_lalr.lalrpop
- lalrpop-test/src/expr_module_attributes.lalrpop
- lalrpop-test/src/generics_issue_104.lalrpop
- lalrpop-test/src/generics_issue_417.lalrpop
- lalrpop-test/src/lifetime_tok.lalrpop
- lalrpop-test/src/loc.lalrpop
- lalrpop-test/src/loc_issue_90.lalrpop
- lalrpop-test/src/nested.lalrpop
- lalrpop-test/src/pub_in.lalrpop
- lalrpop-test/src/sub.lalrpop
- lalrpop-test/src/sub_ascent.lalrpop
- lalrpop-test/src/sub_table.lalrpop
- lalrpop/Cargo.toml
As noted in https://github.com/lalrpop/lalrpop/pull/744#issuecomment-1514099999, #727 did not update the edition in all of the workspace members.
I've taken the liberty to update the two remaining `Cargo.toml` files and update the corresponding tests. I think some 2015 edition idioms were left over?
I was thinking about putting the edition in the workspace toml file using https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table, though that uses Rust 1.64 (related to #742).
> update lalrpop/lalrpop-test to 2021 edition

- doc/calculator/src/calculator2b.lalrpop
- doc/calculator/src/calculator7.lalrpop
- doc/calculator/src/main.rs
- doc/pascal/lalrpop/src/main.rs
- doc/src/lexer_tutorial/001_lexer_gen.md
- doc/whitespace/src/lib.rs
- lalrpop-test/src/error_recovery_span.lalrpop
- lalrpop-test/src/expr_arena_ast.rs
- lalrpop-test/src/inline.lalrpop
- lalrpop-test/src/lib.rs
- lalrpop-test/src/pub_in.rs
- lalrpop-util/src/lib.rs
- lalrpop/src/build/action.rs
- lalrpop/src/build/mod.rs
- lalrpop/src/lexer/re/mod.rs
- lalrpop/src/lr1/codegen/ascent.rs
- lalrpop/src/lr1/codegen/base.rs
- lalrpop/src/lr1/codegen/parse_table.rs
- lalrpop/src/lr1/core/mod.rs
- lalrpop/src/lr1/example/mod.rs
- lalrpop/src/normalize/lower/mod.rs
- lalrpop/src/rust/mod.rs
Inspired by recent movement/discussion. I wanted to take a crack at some of the suppressed clippy lints, largely in generated code which I think hasn't been touched on yet.
In doing so, I also suggest a series of four lints that I think always want to be suppressed or atleast can be handled/fix more specifically.
```
#[allow(clippy::extra_unused_lifetimes)]
#[allow(clippy::needless_lifetimes)]
#[allow(clippy::let_unit_value)]
#[allow(clippy::just_underscores_and_digits)]
```
I roughly tried to keep things to separate commits but am happy to clean the history up/explain things as needed.
> Clippy(mostly in generated code)

- doc/whitespace/src/lexer.rs
- lalrpop-test/src/lib.rs
- lalrpop-test/src/util/mod.rs
- lalrpop/src/build/mod.rs
- lalrpop/src/lexer/dfa/interpret.rs
- lalrpop/src/lexer/dfa/mod.rs
- lalrpop/src/lexer/dfa/overlap.rs
- lalrpop/src/lexer/nfa/mod.rs
- lalrpop/src/main.rs
- lalrpop/src/message/mod.rs
- lalrpop/src/parser/mod.rs
- lalrpop/src/test_util.rs
- lalrpop/src/tok/test.rs
One more pr with clippy lints from `cargo clippy --all-targets`.
With this, there are three sets of lints left.
- Acronym lints which will be fixed with #740 
- unused import in the nested test case #675
- `#[default]` lint #744
Adjusting `Test` in the lexer to use an actual `Range` was non-trivial. The ranges are documented in comments as being inclusive, though the translation to using `RangeInclusive` was a bit more than expected. I think at some times the ranges were actually treated as exclusive as well, as denoted by the tests. I believe it is now consistent, passing tests, and satisfying the clippy lint but that commit could use an extra look.
Using `RangeInclusive` does mean the struct is no longer `Copy` but I don't think that's too much of an issue.
> Clippy --all-targets and RangeInclusive

- tools/ci.sh
The default bash return code is the return code of the last function called.  This means that the CI will only mark as failed if the last command in ci.sh fails.
This can be observed in recent CI runs (for example https://github.com/lalrpop/lalrpop/actions/runs/4765777324/jobs/8471946793) where tests failed, but the CI marked as passed anyways.
> Fail CI if any lines fail

- lalrpop/Cargo.toml
This fixes a compatibility issue with regex 1.8
Closes #750
> Enable 'unicode' feature on regex-syntax

- lalrpop-test/src/expected_tokens_reduce.lalrpop
- lalrpop-test/src/expected_tokens_reduce_lalr.lalrpop
- lalrpop-test/src/lib.rs
- lalrpop-util/src/state_machine.rs
- lalrpop/src/lr1/codegen/parse_table.rs
- lalrpop/src/parser/lrgrammar.rs
This pull request tries to fix the issue described in #736, where the expected tokens given in UnrecognizedToken and UnrecognizedEOF errors include values that would always be rejected if inserted at the error site. The idea is to reuse the existing logic for error recovery in order to filter the expected tokens down to ones which could actually be parsed at the point of the error. The strategy here is:
1. Cause some of the support code for error recovery (specifically `__simulate_reduce()` and `__accepts()`) to always be generated.
Unfortunately this entails some extra code size, even for grammars that don't actually have states where invalid error output could be generated. However, it looks like `__simulate_reduce()` used to always be generated prior to #510 and it doesn't seem like …
> Avoid spurious expected tokens in error output

- lalrpop/src/lr1/build/mod.rs
- lalrpop/src/lr1/codegen/ascent.rs
- lalrpop/src/lr1/core/mod.rs
- lalrpop/src/lr1/error/mod.rs
- lalrpop/src/lr1/first/mod.rs
- lalrpop/src/lr1/lane_table/lane/mod.rs
- lalrpop/src/lr1/lookahead.rs
- lalrpop/src/lr1/state_graph.rs
- lalrpop/src/lr1/tls.rs
Running [samply](https://github.com/mstange/samply) to profile `lalrpop`, I found that most of the time spent during the `LR(1) state construction (lane)` phase is in the `continue_trace` recursive function, which calls `can_shift_nonterminal` in a loop. This last function looks like it should just perform a simple equality on two symbol references, but instead unnecessarily clones a symbol.
Other changes include reducing allocations and minor clippy fixes throughout the entire crate.
I've measured both [Solang] and [Rust Python], which yielded similar times, by using the time printed with the `--level verbose` flag:
-   debug: ~7.9s -> ~6.8s
-   release: ~1.1s -> ~0.45s
[solang]: https://github.com/hyperledger/solang/blob/a14139e916a6a89875d4a1e15c9548d0038b24cd/solang-parser/src/solidity …
> Improve compilation speed by up to 2x

- lalrpop-test/src/lib.rs
https://github.com/lalrpop/lalrpop/issues/675
Imports in extern blocks are only needed in modules, but lalrpop can't currently differentiate that to avoid importing them globally.  Use the workaround suggested in the above linked issue to silence the warning when running test cases
> Allow unused imports in nested test

- Cargo.lock
- Cargo.toml
- doc/calculator/Cargo.toml
- doc/pascal/lalrpop/Cargo.toml
- doc/src/quick_start_guide.md
- doc/src/tutorial/001_adding_lalrpop.md
- doc/whitespace/Cargo.toml
- lalrpop/Cargo.toml
- lalrpop/src/parser/lrgrammar.rs
- version.sh
OK, in my previous PR I failed to update the version number, regenerate the snapshot, etc.
We need to document / streamline this release process.
> release 0.19.10 (take 2)

- .github/pull_request_template.md
- .github/workflows/test.yaml
- Cargo.toml
- lalrpop-test/Cargo.toml
- lalrpop-util/Cargo.toml
- lalrpop/Cargo.toml
> Add rust-version to Cargo.toml and pull request template

- lalrpop/src/lexer/dfa/overlap.rs
- lalrpop/src/lexer/nfa/mod.rs
Working to fix #773. The null case is a little hard, so I think that needs special handling?
One issue I had is with the repeat test as with the new logic, I end up creating a single character range of just 'l'. I added a sort to make things nicer but it might be unnecessary. So this fix might add additional ranges
> Range fix?

- Cargo.lock
- Cargo.toml
- lalrpop/Cargo.toml
#775 has a good example of how to replicate this issue though I wasn't sure how to turn that into a test case.
I'm also trying to keep the feature sets for each dependency consistent. At the top level, we should also explicitly set the version of Regex to 1.8.
Personally, this aggressive use of `default_features = false` doesn't seem worth it but eh.
> Fix issue #775

- .github/workflows/test.yaml
- ci.sh
- lalrpop-test/src/cfg.lalrpop
- lalrpop-test/src/lib.rs
- lalrpop-util/Cargo.toml
- lalrpop-util/src/lib.rs
- lalrpop-util/src/state_machine.rs
- lalrpop/Cargo.toml
- lalrpop/src/normalize/token_check/mod.rs
- lalrpop/src/test_util.rs
The tests are currently run with all features enables which hides breakage when some are note defined.
This should help capture future issues.
**Note 1:** this PR removes a check in `normalize::token_check` that prevented most tests from running.
I am not sure about the extent of that change but all the tests now build & pass success-fully regardless of the enabled features.
**Note 2:** The subtlety of enabling the regex's and regex-syntax unicode feature for the specific needs of the grammar used, while totally sensible, is a bit unintuitive.
That's mostly because it is a transitive dependency and one does not expect it to break in such a way.
This might be worth stressing in the documentation.
> Fix building issues when not all features are enabled at once.

- .github/workflows/test.yaml
- Cargo.lock
- Cargo.toml
- doc/calculator/Cargo.toml
- doc/nobol/Cargo.toml
- doc/pascal/lalrpop/Cargo.toml
- doc/src/quick_start_guide.md
- doc/src/tutorial/001_adding_lalrpop.md
- lalrpop-test/Cargo.toml
- lalrpop-test/src/cfg.lalrpop
- lalrpop-test/src/lib.rs
- lalrpop-util/Cargo.toml
- lalrpop-util/src/lib.rs
- lalrpop-util/src/state_machine.rs
- lalrpop/Cargo.toml
- lalrpop/src/lexer/nfa/test.rs
- lalrpop/src/lr1/build/test.rs
- lalrpop/src/normalize/token_check/mod.rs
- lalrpop/src/normalize/token_check/test.rs
- lalrpop/src/test_util.rs
- tools/ci.sh
This is a "frontport" of #783.
This sligtly deviates from the afore-mention PR to adapt to the changes on `master` and hopfully for the better.
> Introdude `unicode` and fix various test cases when not all features are enabled.

- Cargo.lock
- Cargo.toml
- lalrpop/src/lexer/nfa/mod.rs
- lalrpop/src/lexer/nfa/test.rs
- lalrpop/src/normalize/token_check/mod.rs
Taking a crack at upgrading regex-syntax.
Some of the non-trivial changes that could use a second look are with the new handling of Literal and all of the Anchor/Boundary stuff being converted into this Look(with the corresponding change to the error handling).
> Upgrade regex-syntax to 0.7 #757

- .github/workflows/test.yaml
- Cargo.lock
- Cargo.toml
- lalrpop/Cargo.toml
There has been some previous discussion about managing dependency resolution. I think that the more of this that can be offloaded to the ci, the better. This pr adds a minimum versions check to the ci inspired by https://users.rust-lang.org/t/psa-please-specify-precise-dependency-versions-in-cargo-toml/71277 and enabled by https://github.com/rust-lang/cargo/pull/11688.
The rest of the changes are to satisfy the minimum set of versions/features that can build lalrpop with the current Cargo.toml files.
> Minimal versions

- .github/workflows/test.yaml
An alternative option to #755.  This pulls cargo update out of ci.sh into the test.yaml, and uses a matrix strategy to run all tests with both the existing Cargo.lock and cargo update run, for each toolchain version.
> Add a matrix to run all tests both with and without cargo update

- .github/workflows/test.yaml
- tools/ci.sh
With the addition of `cargo hack` into the `ci.sh` script, the github workflows run has significantly slowed down. This also makes it more inconvenient to add further things to the workflow like #790. I think the workflow should prioritize failing fast and speed.
To this end, I've moved the `cargo hack test` call out of the `ci.sh` script into it's own workflow. This invocation is a bit heavy weight to be the first thing a contributor runs and can be better parallelized on it's own. Maybe something like https://github.com/taiki-e/cargo-hack/pull/180.
Note I've ignore two features from the `cargo hack` invocation: `pico-args` and `default`. `pico-args` is only needed for the cli so it's unnecessary to include with the tests.`default` is excluded because it added an extra unnecessary …
> Move cargo hack to it's own workflow and cleanup

- lalrpop-test/src/lexer_generic_lib.rs
- lalrpop/src/lexer/dfa/overlap.rs
I was poking around at the compile times and I realized there was an incredible amount of error printing going on. Seems like some debugging code got merged, whoops. Removing these saves at least a minute in `cargo hack test`.
> Remove some debugging statements

- .github/workflows/test.yaml
This is so that we don't waste resources on the heaviest test if we're just going to fail on format or similar.
It does lengthen the CI runtime by a little bit, but that's async anyways.
> [RFC] Don't run feature-powerset test until after linting

- doc/src/lexer_tutorial/001_lexer_gen.md
Clarify the new unicode feature, and add suggestions for avoiding the unicode dependency if it's not needed.  Some users may be depending on unicode without intending to, so give them migration tips to avoid the requirement.
> Describe lexer unicode support in the book

- Cargo.lock
- Cargo.toml
- RELEASES.md
- doc/calculator/Cargo.toml
- doc/nobol/Cargo.toml
- doc/pascal/lalrpop/Cargo.toml
- doc/src/quick_start_guide.md
- doc/src/tutorial/001_adding_lalrpop.md
- doc/whitespace/Cargo.toml
- lalrpop/Cargo.toml
- lalrpop/src/parser/lrgrammar.rs
> Release 0.20.0

- lalrpop/src/api/mod.rs
- lalrpop/src/lib.rs
Given the comment on process_root_unconditionally, seems like there could be an additional annotation to help elevate this.
> Add deprecation notice for process_root_unconditionally

- doc/src/tutorial/001_adding_lalrpop.md
- When I run `cargo init` it produces a `Cargo.toml` file with `edition = "2021"` in it. 
- When I went through [Adding LALRPOP to your Cargo.toml file](https://lalrpop.github.io/lalrpop/tutorial/001_adding_lalrpop.html) in the tutorial I only updated the `[build-dependencies]` and `[dependencies]` sections not thinking about the `edition` in the `[package]` section at all.
- I got a bunch of errors shown below. 
- Three options that fixed the errors for me were:
1: Changing the edition to "2018" in `Cargo.toml`
2: Removing the edition from `Cargo.toml`
3: Keeping the edition at "2021" and adding 
`lalrpop = "0.19.8"` to the `[dependencies]`
in the `Cargo.toml` file
I'm still new to Rust, but I don't think I've customized `cargo init` in a way that makes it add the edition. I'm assuming …
> Modify Cargo.toml example to contain edition

- lalrpop/Cargo.toml
- lalrpop/src/lib.rs
The `diff` crate is only used for tests, so move it to `dev-dependencies`. This should mean end users have one less crate to download and build.
> Move dependency on `diff` crate to `dev-dependecies`

- doc/src/tutorial/001_adding_lalrpop.md
The regex dependency is not and should not be a dependency of crates depending on lalrpop (unless they need regex directly).  This was presumably added to work around lalrpop's previous feature underspecification, but is no longer needed.  Using the built-in lexer works just fine with the normal dependencies, indirectly pulling lalrpop's regex dependency.
> Drop mention of adding regex dependencies from book.

- doc/calculator/Cargo.toml
- doc/calculator/build.rs
- doc/nobol/Cargo.toml
- doc/nobol/build.rs
- doc/nobol/src/main.rs
- doc/pascal/lalrpop/Cargo.toml
- doc/pascal/lalrpop/build.rs
- doc/pascal/lalrpop/src/main.rs
- doc/src/advanced_setup.md
- doc/src/quick_start_guide.md
- doc/src/tutorial/001_adding_lalrpop.md
- doc/src/tutorial/002_paren_numbers.md
- doc/src/tutorial/006_macros.md
- doc/src/tutorial/007_fallible_actions.md
- doc/whitespace/Cargo.toml
- doc/whitespace/build.rs
- doc/whitespace/src/lib.rs
- doc/whitespace/src/main.rs
- lalrpop-test/Cargo.toml
- lalrpop-test/build.rs
- lalrpop-test/src/lib.rs
- lalrpop-test/src/pub_in.rs
- lalrpop-test/src/user_defined_error_visibility.rs
- lalrpop/src/lib.rs
- lalrpop/src/main.rs
Hello, I was looking through the docs again to write a parser and I realized they have some excess code in the form of `extern crate lalrpop;` and setting the build file to `build.rs` which is the default.
I've gone through and done my best to remove these throughout the code base.
> Modernize extern crate

- lalrpop/src/build/mod.rs
Closes #808 
This pr will ignore any erroneous symlinks when looking for lalrpop files and will not propagate up the error.
The related issue also mentions adding some kind of warning message. I'm not sure how/if such a thing should be added especially since we are otherwise skipping over this error(So it would mean using `eprintln` I guess?).
Better error messages would certainly be more helpful but in this case lalrpop is just propagating up whatever https://doc.rust-lang.org/std/io/type.Result.html gives us so poor error messages seem like a libs team issue https://github.com/rust-lang/rfcs/issues/2885.
> Filter out NotFound errors

- lalrpop/src/build/action.rs
- lalrpop/src/lexer/intern_token/mod.rs
- lalrpop/src/lr1/codegen/ascent.rs
- lalrpop/src/lr1/codegen/base.rs
- lalrpop/src/lr1/codegen/parse_table.rs
- lalrpop/src/lr1/codegen/test_all.rs
- lalrpop/src/parser/lrgrammar.rs
I've procrastinated a little bit by seeing what happens if `clippy::all` was removed from the generated code.
In some cases it just meant making the lints more precise in what was being allowed(like `needless_lifetimes`, `just_underscores_and_digits`, etc).
It did catch that in a couple places `#[cfg_attr(rustfmt, rustfmt_skip)]` was being emitted which has been deprecated in favor of `#[rustfmt::skip]`. There were a bunch of unnecessary clones that have been removed.
It also suggests adding a `Default` impl to any parsers that are generated which might have a niche application with the more built-in support for default Rust has been getting.
There were two cases where trivial math was being generated like `* 1` and `1 - 1` that I removed(which are actually clippy errors not warnings). …
> miscellaneous clippy/cfg_attr rustfmt deprecations

- lalrpop-test/src/lib.rs
- lalrpop/src/lexer/nfa/test.rs
- lalrpop/src/lr1/build/test.rs
- lalrpop/src/lr1/codegen/base.rs
- lalrpop/src/lr1/codegen/parse_table.rs
- lalrpop/src/lr1/error/test.rs
- lalrpop/src/lr1/trace/trace_graph/mod.rs
- lalrpop/src/normalize/prevalidate/test.rs
- lalrpop/src/normalize/token_check/mod.rs
- lalrpop/src/normalize/token_check/test.rs
- lalrpop/src/parser/lrgrammar.rs
- lalrpop/src/tok/test.rs
With the new clippy release, I've gone through and either manually or `cargo clippy --fix`ed the triggered lints. I don't think anything here is particularly interesting/useful but may as well not let things slip.
> Clippy 1.72 release fixes

- doc/src/advanced_setup.md
- doc/src/generate_in_source.md
- lalrpop/src/build/mod.rs
Hello. I would like to start addressing some of the issues raised around lalrpop's Configuration settings for setting paths and such. There are a couple relevant issues that I think should be address on the way to a potential 1.0(since they may involve/give the chance to making breaking changes).
Maybe there is a more radical change with configurations that should be made, but I don't have the high level overview to  make that call.
Here are the following issues I would like to address eventually, I'm open to suggestions/feedback. #545 #611 #677 #690 #699 #710 (maybe #539)
So far, this pr adds a little bit of documentation for the rerun directives and looks at identifying ill named Rust modules from file names. The latter would be a warning of the form `eprintln` except that cargo will …
> LALRPOP Configuration fixes

- doc/src/tutorial/009_state_parameter.md
> Mention the requirement that state parameters implement Copy in the tutorial

- doc/src/conditional-compilation.md
> Typo conditional-compilation.md

- doc/src/SUMMARY.md
I never knew lalrpop had some support for `#[cfg(feature = "cool")]`. It doesn't seem to render on the documentation. I think this is the way to fix it?
> Update SUMMARY.md with conditional compilations page

- .github/workflows/test.yaml
- Cargo.lock
- Cargo.toml
- lalrpop/Cargo.toml
- lalrpop/src/build/mod.rs
The same functionality as `is_terminal::is_terminal` is now provided by `std::io::IsTerminal::is_terminal()`
> Remove dependency on `is-terminal` crate

- .github/workflows/test.yaml
- Cargo.lock
- Cargo.toml
- lalrpop-util/Cargo.toml
- lalrpop-util/src/lexer.rs
- lalrpop/src/lexer/intern_token/mod.rs
I'm a developer of [paguroidea](https://github.com/SchrodingerZhu/paguroidea). After we benchmarked several parsers, we noticed that lalrpop was abnormally slow. So I decided to dig up the reason. And it turned out to be the problem of the lexer. This PR aims to improve the lexing performance, making it a bit more decent.
- Set the default `skip` rule from `\s*` to `\s+`. If the match is empty, why do we bother to skip it? This change boosted throughput from 4.5 MBps to 5.5 MBps in our JSON benchmark.
- Set an ASCII `skip` rule when "unicode" feature is disabled. Purely an ergonomic improvement.
- Rewrite the lexer, directly use the underlying `regex-automata`, which gives us more control to achieve better performance. This change boosted throughput from 5.5 MBps to 138 MBps in our JSON …
> Let's booooooost!

- Cargo.lock
- lalrpop/Cargo.toml
Itertools changelog: https://github.com/rust-itertools/itertools/blob/master/CHANGELOG.md
We don't use any of the functionality with breaking changes.  This is just about getting on the latest version so we keep getting fixes.
> Bump itertools dep to 0.11

- Cargo.lock
- doc/src/quick_start_guide.md
- lalrpop/src/lexer/nfa/mod.rs
- lalrpop/src/lr1/first/mod.rs
- lalrpop/src/lr1/lane_table/table/mod.rs
- lalrpop/src/tok/test.rs
- A typo in the docs around lalrpop version for commented out alternative
- A slightly more "stylistic" implementation of PartialOrd/Ord for Test(Avoiding an unwrap)
- Use a bunch of `.*_default()`
> Doc Typo and New Clippy Lints

- doc/src/tutorial/001_adding_lalrpop.md
As addressed in issue #750 the regex breaks the build. In this case the current [tutorial](https://lalrpop.github.io/lalrpop/tutorial/001_adding_lalrpop.html) does not import unicode which causes the very first example form the tutorial to fail with the error. 
```
called 'Result::unwrap()' on an 'Err' value: Syntax(
regex parse error:
^(\s*)
^^
error: Unicode-aware Perl class not found (make sure the unicode-perl feature is enabled)
)
```
This is all because the unicode ~crate~ feature is not imported in the cargo.toml, (like it is in the [source file](https://github.com/lalrpop/lalrpop/blob/master/doc/calculator/Cargo.toml)) adding is there fixes the issue.
> add 'unicode' to tutorial import

- lalrpop-test/src/lib.rs
- lalrpop-test/src/zero_length_match.lalrpop
- lalrpop-util/src/lexer.rs
If a zero length skip pattern was the longest match, we were supplied an invalid token.  The current code infinite loops in this state.
> Restore test for zero length skip matches

- Cargo.lock
- Cargo.toml
Changelog here: https://github.com/rust-lang/regex/blob/master/CHANGELOG.md#1100-2023-10-09
The gist is that regex added support for new word-boundary matching characters, which required changes in the regex_syntax and regex_automata APIs.  Those changes aren't breaking in our use case.
In order to stay on the latest fixes and also unify with regex (which we also depend on directly and itself depends on syntax 0.8 and automata 0.4), bump to the newest semver series.
"cargo outdated" doesn't detect these due to this bug: https://github.com/kbknapp/cargo-outdated/issues/360
I just happened to notice them while checking "cargo tree" on another issue.  We should try to keep a casual eye on our workspace dependencies going forward.
> Update regex-syntax and regex-automata across breaking change

- lalrpop/src/lexer/re/mod.rs
regex_syntax::parse() converts our regex strings into the HIR of the regex, part of that includes unpacking various metacharacters into a list of symbols.  In many cases, this expansion changes depending if it should expand into unicode or not.
Prior to #814, we were still outputting unicode regexes unconditionally, but regex internals seem to be compiling them away and avoiding errors. The switch in #814 caused these to be result in real errors.
Follow-up work will be needed to determine why existing tests didn't detect this.
> Only generate unicode tokens if the unicode feature is enabled

- Cargo.lock
- Cargo.toml
- RELEASES.md
- doc/calculator/Cargo.toml
- doc/nobol/Cargo.toml
- doc/pascal/lalrpop/Cargo.toml
- doc/src/quick_start_guide.md
- doc/src/tutorial/001_adding_lalrpop.md
- doc/whitespace/Cargo.toml
- lalrpop/src/parser/lrgrammar.rs
- version.sh
This is an attempt to "kick-the-tires" on a new release based on https://github.com/orgs/lalrpop/discussions/823.
I did an initial draft of the release notes in `RELEASES.md` and ran `./version.sh` to update the version number in all the places.
> Release 0.20.1

- .github/workflows/book.yml
- .github/workflows/deploy.yml
- .github/workflows/test.yaml
- lalrpop/src/lr1/mod.rs
- lalrpop/src/util.rs
- Removes 2 unused imports
- Upgrades to `actions/checkout@v4`
> Minor cleanup

- doc/src/tutorial/index.md
Following up on https://github.com/lalrpop/lalrpop/pull/842#discussion_r1362300955
> Include a pointer from the tutorial to a collection of examples

- lalrpop-test/src/lib.rs
- snap.sh
- version.sh
As in #593 it seems like lalrpop has two shell scripts that do the same thing, so lets simplify that.
> Fix #593, remove snap.sh

- lalrpop/src/build/mod.rs
- lalrpop/src/tok/mod.rs
- lalrpop/src/tok/test.rs
Add support for block comments including nesting.
Fixes #370
> Grammar file block comment support

- lalrpop-util/LICENSE-APACHE
- lalrpop-util/LICENSE-MIT
- lalrpop/LICENSE-APACHE
- lalrpop/LICENSE-MIT
Closes #600 
I don't fully understand the license implications here but from my reading, the correct solution from cargo has not fully manifested yet. In looking what other projects like tokio/regex do, they include the license files in each project so it seems reasonable to follow that strategy.
See https://github.com/bytecodealliance/wasmtime/pull/4664 https://github.com/tokio-rs/tracing/pull/842 https://github.com/rust-lang/cargo/issues/8537 for some discussion on these issues.
> Add symlinks to license files

- Cargo.lock
- lalrpop/Cargo.toml
- lalrpop/src/build/mod.rs
The lalrpop_files function traverses recursively into subdirectories of the provided root directory and returns all .lalrpop files. However, lalrpop_files used to skip symlinks to directories because it used the DirEntry::file_type method to detect directories, which doesn't follow symlinks. Since lalrpop_files does follow symlinks to files, this old behavior for symlinks was inconsistent and unintuitive.
With this commit, we're now using the Path::is_dir method, which does follow symlinks, so now lalrpop_files traverses also into symlinks to directories.
> Traverse into symlinks to dirs

- lalrpop-util/Cargo.toml
- lalrpop/Cargo.toml
We get breakage if lalrpop and lalrpop-util are not consistent, but the defaults aren't consistent
> Set unicode as a default feature in lalrpop-util

- RELEASES.md
- doc/src/advanced_setup.md
- lalrpop/src/build/mod.rs
- lalrpop/src/lr1/build_lalr/mod.rs
- lalrpop/src/normalize/precedence/mod.rs
- lalrpop/src/parser/lrgrammar.rs
- lalrpop/src/parser/test.rs
Addresses the documentation confusion with #862 and some of the new clippy lints.
> Consistent LALR docs and clippy

- lalrpop/src/build/mod.rs
- lalrpop/src/lr1/lane_table/table/mod.rs
- lalrpop/src/parser/lrgrammar.rs
> <= Rust 1.76 lints

- doc/src/SUMMARY.md
- doc/src/cheatsheet.md
I think the idea of a feature list "cheatsheet" is a great idea as suggested in #387. I've done a pretty minimal adaptation of the table elements suggested in that list with their corresponding links.
I don't have a clear idea of the right way to present this, so open to all suggestions.
> Kick the tires on a documentation cheatsheet

- Cargo.lock
- Cargo.toml
- RELEASES.md
- doc/calculator/Cargo.toml
- doc/nobol/Cargo.toml
- doc/pascal/lalrpop/Cargo.toml
- doc/src/quick_start_guide.md
- doc/src/tutorial/001_adding_lalrpop.md
- doc/whitespace/Cargo.toml
- lalrpop/src/parser/lrgrammar.rs
As noted in #864 and #848, it's probably safe to cut a new release? There have been a few changes since 0.20.1 but most of them are minor or documentation related. I've noted the new features in the updated release notes as I understand them.
> Release 0.20.2

- doc/src/quick_start_guide.md
- doc/src/tutorial/001_adding_lalrpop.md
Tried to make it clearer that the generated files are by default saved to `OUT_DIR`, and gave an example of `include!()`-ing the generated files.
> Add 'OUT_DIR' to quick start and tutorial

- doc/src/tutorial/001_adding_lalrpop.md
I saw this note in the docs and it surprised me. I tracked this back to a commit over 9 years ago: 0983cec. In looking through the issue tracker, this might have been fixed as early as 2 weeks later in #30. Regardless, Lalrpop now uses cargo's `rerun-if-changed` directive so this is outside of Lalrpop's scope.
> Remove outdated note?

- Cargo.lock
- Cargo.toml
- doc/lexer/Cargo.toml
- doc/lexer/build.rs
- doc/lexer/src/ast.rs
- doc/lexer/src/grammar.lalrpop
- doc/lexer/src/lexer.rs
- doc/lexer/src/lib.rs
- doc/lexer/src/main.rs
- doc/lexer/src/tokens.rs
- doc/src/lexer_tutorial/005_external_lib.md
I'm interested in addressing #869. Before upgrading the version of logos, I would first like to add a testable version of the logos lexer example. This involves extracting out the example into it's own `doc/lexer` repo(Which is an unfortunate duplication given how documentation is generated). However in doing so I've run across some trivial issues in the documentation that I've addressed.
One part I'm not sure how to address is `the trait bound `Token: __ToTriple` is not satisfied` because `trait `__ToTriple` is not implemented for `Token``. Maybe I'll get around to figuring it out at some point. Until then, I'm leaving this pr here as a first step.(If someone knows the answer or wants to give it a try, feel free to suggest a edit).
> First step to add a lexer example in tree

- Cargo.toml
- lalrpop/Cargo.toml
The _ variants of several Cargo fields will be deprecated in the 2024 edition.  Switch to the recommended - variants.
https://github.com/rust-lang/cargo/pull/13783
> Use default-features in favor of default_features

- lalrpop/src/lr1/codegen/base.rs
- lalrpop/src/parser/lrgrammar.rs
As suggested by @Pat-Lafon in #889
> Move the ' ' character in generated typebounds to the second clause

- Cargo.lock
- lalrpop/Cargo.toml
- lalrpop/src/build/mod.rs
The sha3 library seems more widely used and actively maintained.
All we do with these hashes is save the hash in the output file and compare to determine if we need a rebuild.
> Switch out the tiny_keccak hashing library for the sha3 library

- lalrpop/src/api/mod.rs
- lalrpop/src/normalize/macro_expand/mod.rs
- lalrpop/src/normalize/macro_expand/test.rs
- lalrpop/src/normalize/mod.rs
- lalrpop/src/normalize/tyinfer/test.rs
- lalrpop/src/session.rs
> Detect deep recursion when expanding macros and error out

- Cargo.lock
- lalrpop/Cargo.toml
- lalrpop/src/lr1/codegen/parse_table.rs
Switch deprecated group_by() to chunk_by()
The change in name was made because chunk_by() better implies that the function groups *consecutive* elements (rather than searching through the iterator and funding *all* matching elements).  This raises the question of whether the intention in the original group_by() was correct, since the change was made to avoid subtle bugs around assuming that this grouped all entries rather than consecutive entries.  In the two instances we have of this function call, the first one has a comment specifically calling out a desire to do this consecutively.  In the second, the iterator was previously sorted by the chunking value, making consecutive equivalent to all, so I believe we are free of this potential bug.
> Update to itertools 0.13

- doc/src/quick_start_guide.md
Closes a code block which wasn't previously closed
> Fix quick_start_guide.md

- lalrpop/src/lr1/lane_table/construct/merge.rs
- lalrpop/src/lr1/lane_table/lane/mod.rs
- lalrpop/src/lr1/lane_table/test.rs
We need to make sure the state in the conflict is in the lane table. All the existing test cases happened to have a shift case in the conflict state, even if the shift wasn't part of the actual conflict. In the event of a conflicting state with only reduce actions, we'll need the lookahead store, so we can check it as a successor of the predecessors we found.
fixes #897
> Insert an empty lookahead in the lane table in reduce conflict states

- lalrpop/src/grammar/repr.rs
- lalrpop/src/normalize/lower/mod.rs
- lalrpop/src/parser/mod.rs
Nightly on rust 1.80 has expanded some of the dead_code checking to hit a few cases that weren't hit before.  Clean those up.
> Clean up new nightly dead code warnings

- lalrpop/src/build/action.rs
- lalrpop/src/parser/lrgrammar.rs
> Make clippy happy in generated lookaround action code

- lalrpop-util/src/lib.rs
Resolves #909  
This is a documentation only change. All tests pass on using
```
stable-aarch64-apple-darwin (default)
rustc 1.78.0 (9b00956e5 2024-04-29)
```
To see effect, run `cargo doc` and then look at `./target/doc/lalrpop_util/macro.lalrpop_mod.html`
> Document $attr in lalrpop_mod!

- lalrpop/src/lr1/error/mod.rs
https://github.com/lalrpop/lalrpop/blob/d7daf3ff1f1fe14727e5a034a30f368ec8c7f244/lalrpop/src/lr1/error/mod.rs#L368
> Fix error msg `LALROP` to `LALRPOP`

- Cargo.lock
- Cargo.toml
- doc/lexer-modes/Cargo.toml
- doc/lexer-modes/build.rs
- doc/lexer-modes/src/grammar.lalrpop
- doc/lexer-modes/src/lexer.rs
- doc/lexer-modes/src/lib.rs
- doc/lexer-modes/src/main.rs
In some languages, it is necessary for the parser to control the lexer's mode.  This is possible, but non-obvious.
This commit adds a simple example that shows how to parse the "list of length-value" language in which values are encoded as a length, followed by a colon, and then the literal number of bytes, e.g., `2:hi`.  To parse this, the parser need to tell the lexer to return the next `n` literal bytes when it sees the length prefix.
See #802.
> Add an example showing how the parser can control the lexer's mode.

- Cargo.lock
- lalrpop/Cargo.toml
The main change in bit-set 0.6 is bumping their bit-vec depenendency to 0.7.  bit-vec has a number of performance improvements and bug fixes in
the new release.
While we're looking at versions, update Cargo.lock to grab the latest versions of everything.
> Bump bit-set to 0.6

- lalrpop/src/lr1/build/mod.rs
Commit a928c53f668ffc557448266375e94c309d7b8f01 changed the logic to move reduce/reduce detection into the same function with shift/reduce detection, but didn't update the comment
> Fix comment about conflict detection

- lalrpop/src/lib.rs
Add an exception for main.rs.  exit() calls are unexpected behavior in a library, where the caller should have control on whether errors are fatal or not.  In binaries, there is no caller and the arguments against exit() are weaker.  In many cases, exit() may still be a control-flow anti-pattern, but exceptions exist, so allow this for everything that's definitely only in a binary context.
Regardless of the allow() in main.rs, the clippy lint contains an exception for exit calls in entrypoint functions, so the existing exit() call, which is in fn main() does not trigger this lint, even without the allow() attribute.
> Lint on calls to process::exit()

- doc/lexer-modes/src/lexer.rs
Byte arrays are more cleanly represented as byte strings
> Fix clippy issues in new nightly 1.82.

- doc/calculator/build.rs
- doc/lexer-modes/build.rs
- doc/lexer/build.rs
- doc/nobol/build.rs
- doc/src/advanced_setup.md
- doc/src/quick_start_guide.md
- doc/whitespace/build.rs
- lalrpop/src/api/mod.rs
- lalrpop/src/lib.rs
Update the docs to recommend this as the top choice for setting up lalrpop.
Prior to this commit, the book incorrectly stated that `process_root()` looked in `./src`, while the documentation comments in the code correctly identified it as parsing the current directory.  Switching the book to recommend `process_src()` addresses this inconsistency as well.
> Add a new process_src() public helper to look in the source directory.

- lalrpop/src/api/mod.rs
> Process src nits

- README.md
Updating the links in the README from `http://lalrpop.github.io` to `https://lalrpop.github.io`.
They are currently broken because no http->https redirect is configured for the github page.
> update doc links in README.md

- Cargo.lock
- Cargo.toml
- RELEASES.md
- doc/calculator/Cargo.toml
- doc/lexer-modes/Cargo.toml
- doc/lexer/Cargo.toml
- doc/nobol/Cargo.toml
- doc/pascal/lalrpop/Cargo.toml
- doc/src/quick_start_guide.md
- doc/src/tutorial/001_adding_lalrpop.md
- doc/whitespace/Cargo.toml
- lalrpop/Cargo.toml
- lalrpop/src/parser/lrgrammar.rs
As has been noted in other issues, there have been two nice bug fixes that probably warrant a new release. We can wait on #901(though I don't think that's a breaking change) to bundle everything together or we can release what we currently have now and then have a point release when #901 gets merged.
Feel free to make any changes to the release notes as needed.
> Cut a 0.21.0 release

- lalrpop/src/api/mod.rs
1.82 clippy is complaining about some of our initial paragraphs being
too long.  More details here: https://rust-lang.github.io/rust-clippy/master/index.html#/too_long_first_doc_paragraph
I didn't limit this to just the instances clippy flagged, but went through and tried to generally reword the api docstrings to start with a short summary paragraph and then elaborate in a second paragraph.
> Start docstrings with short summary paragraph

- lalrpop/src/build/mod.rs
- lalrpop/src/parser/lrgrammar.rs
It was open coding the same functionality anyways, so this is just better.
As a side effect, it dodges a new warning in rust 1.82 for unreachable code triggered by the whitespace example
> Switch to_triple to use Result::map_err()

- lalrpop/Cargo.toml
This lets us call the lalrpop binary using "cargo run" rather than "cargo run --bin lalrpop".  If we want to call some other binary we can still use --bin (eg "cargo run --bin calculator").
> Add default-run to lalrpop package specification

- Cargo.lock
- lalrpop/Cargo.toml
There don't seem to be major user facing changes here.  The big change is that bit-set 0.8 bumps the transitive bit-vec dependency to 0.8 as well, and bit-vec seems to have some minor cleanups and performance improvements
> Bump bit-set dependency to 0.8

- lalrpop/src/lr1/lane_table/table/mod.rs
Clippy 1.83 doesn't like that we specified the lifetime in the argument, but elided it in the return.
> Fully elide lifetimes

- lalrpop-util/src/lib.rs
Usually we write
```rust
use lalrpop_util::lalrpop_mod;
lalrpop_mod!(pub grammar);
```
but if you write
```rust
lalrpop_util::lalrpop_mod!(
// No parser should have been generated so nothing should be unused
#[deny(dead_code)]
cfg
);
```
this will fail with
```sh
error: cannot find macro `lalrpop_mod` in this scope
--> doc/cfg/src/lib.rs:1:1
|
1 | / lalrpop_util::lalrpop_mod!(
2 | |     // No parser should have been generated so nothing should be unused
3 | |     #[deny(dead_code)]
4 | |     cfg
5 | | );
| |_^
|
= note: this error originates in the macro `lalrpop_util::lalrpop_mod` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this macro
|
1 + use lalrpop_util::lalrpop_mod;
|
```
> prepend lalrpop_util:: to lalrpop_mod rec call

- doc/calculator/src/main.rs
> clippy warning about no longer needed import from #944

- Cargo.toml
- lalrpop-util/Cargo.toml
- lalrpop-util/src/lexer.rs
- lalrpop/Cargo.toml
This unlinks the `lexer` feature from the `std` feature. While expanded `no_std` support is possible in `lalrpop`, this is the key component that prevents using a the lexer within a `no_std` environment.
In order to do this, the `regex-automata` crate needs to have the `perf` feature removed, because it implies the `perf-literal-multisubstring` feature, which implies the `std` feature. To minimize the changes caused by this, the `perf` feature is re-enabled for the `std` feature of the `lalrpop-util` crate.
> Add `no_std` support for `lalrpop-util` crate with `lexer` feature

- lalrpop-util/src/lib.rs
- lalrpop/src/build/mod.rs
- lalrpop/src/lr1/trace/shift/mod.rs
- lalrpop/src/parser/lrgrammar.rs
to
Clippy is concerned that if there's whitespace, we might have intended those comments or attributes to apply to something else
> Avoid whitespace between doc comments or attributes and what they apply

- version.sh
This could probably be lumped in the doc case, but that case is a little weird in that it assumes that any dependency with the old version number is a lalrpop dependency.  So if we happened to have some third party dependency on the same version number as the old lalrpop version in the doc examples, the script would update that too.  So rather than propagating that bug into the larger and more impactful lalrpop Cargo.toml handling, just special case it.
> Fix version.sh to update lalrpop's lalrpop-util dependency

- version.sh
This really only removes one special casing situation, but it seems somewhat more comprehensive and covers the comment case that was missed before
> Kind of unify version.sh regex search

- lalrpop/src/lr1/codegen/parse_table.rs
- lalrpop/src/parser/lrgrammar.rs
Since these are user-supplied, this can help them diagnose bugs
> Turn a few warnings back on when we match token values

- .github/workflows/test.yaml
- Cargo.lock
- Cargo.toml
- lalrpop-util/Cargo.toml
- lalrpop-util/src/lib.rs
This uses `core::error::Error` instead of `std::error::Error` when the `std` feature is not enabled.
As a result, the MSRV is 1.81 when the `std` feature is not enabled, but unchanged when the `std` feature is enabled.
> Support `Error` with `std` feature disabled

- Cargo.lock
- lalrpop/Cargo.toml
The main change in ascii-canvas is also the term 1.0 fix.  Bumping to term 1.0 gets us several bugfixes, and a nice dependency tree reduction.
> Update to ascii-canvas 4.0 and term 1.0

- Cargo.lock
Semantic merge conflict between #963 and #957 caused rustversion to get dropped from Cargo.lock
> Lock rustversion

- lalrpop/src/file_text.rs
- lalrpop/src/lr1/error/mod.rs
- lalrpop/src/lr1/error/test.rs
The existing error messages assume that the source of a reduce/reduce conflict is which nonterminal is reduced to.  This is a confusing result if there are two possible reductions to the same nonterminal ("I can reduce to an A, but I can also reduce to an A").  Identical reductions to the same nonterminal are easy to do and can be hard to spot in the presence of macros.
This error message detects when the conflict is for the same nonterminal and helpfully points to the specific rules in that nonterminal that conflict.
> Add a new error message for ambiguous reductions to the same nonterminal

- lalrpop/src/lr1/error/mod.rs
the first.
On conflicts, lalrpop tries every possible lookahead token to find good conflict examples.  On shift/reduce conflicts that makes a lot of sense, different lookahead tokens are different conflicts, because the shift is different.  On reduce/reduce conflicts on the other hand, the lookahead is sort of irrelevant.  Hopefully, at least one lookahead produces a good example, so we won't need naive errors at all.  The fact that we only found naive errors means that none of the lookaheads were helpful. So rather than reporting one error message per token, just drop all but the first, since we can't tell what lookahead is more helpful (if we'd found a helpful lookahead, we'd be using that for a better error).
> When encountering naive errors on reduce/reduce conflicts, drop all but

- Cargo.lock
- Cargo.toml
- RELEASES.md
- doc/calculator/Cargo.toml
- doc/cfg/Cargo.toml
- doc/lexer-modes/Cargo.toml
- doc/lexer/Cargo.toml
- doc/nobol/Cargo.toml
- doc/pascal/lalrpop/Cargo.toml
- doc/src/quick_start_guide.md
- doc/src/tutorial/001_adding_lalrpop.md
- doc/whitespace/Cargo.toml
- lalrpop/Cargo.toml
- lalrpop/src/parser/lrgrammar.rs
For discussion.  In my opinion, I'd like to at a minimum get the following tasks done first:
Happy to add any other release blockers you all want.  I'm willing to take on all of the above, except the two PRs I mentioned need code reviews from someone else.
> Release version 0.22.0

- doc/calculator/src/ast.rs
- doc/lexer-modes/src/lexer.rs
- doc/lexer/src/lexer.rs
- doc/whitespace/src/lexer.rs
- lalrpop-test/src/lexer_generic_lib.rs
- lalrpop-test/src/util/mod.rs
- lalrpop-util/src/lexer.rs
- lalrpop/src/lexer/dfa/mod.rs
- lalrpop/src/lr1/build/mod.rs
- lalrpop/src/lr1/codegen/parse_table.rs
- lalrpop/src/lr1/core/mod.rs
- lalrpop/src/lr1/lane_table/construct/merge.rs
- lalrpop/src/lr1/lane_table/table/mod.rs
- lalrpop/src/lr1/lookahead.rs
- lalrpop/src/lr1/report/mod.rs
- lalrpop/src/lr1/trace/reduce/mod.rs
- lalrpop/src/lr1/trace/shift/mod.rs
- lalrpop/src/lr1/trace/trace_graph/mod.rs
- lalrpop/src/normalize/inline/mod.rs
- lalrpop/src/normalize/prevalidate/mod.rs
- lalrpop/src/normalize/resolve/mod.rs
- lalrpop/src/normalize/token_check/mod.rs
- lalrpop/src/rust/mod.rs
- lalrpop/src/util.rs
Tracking lifetime support in impls was added in recent nightly clippy.
https://github.com/rust-lang/rust-clippy/pull/13286
> Elide needless lifetimes in impls

- README.md
* Add docs.rs links for our autogenerated API docs
* Fix the example project links to 1. Link to the most recent version instead of a specific commit from years ago 2. Point at the new RustPython location, since they have migrated their parser into a separate repo.
> Update and fix README links

- lalrpop/src/normalize/cond_comp/test.rs
> 1.82 clippy lint

- lalrpop/src/generate.rs
- lalrpop/src/test_util.rs
Recommended by clippy 1.83.  I missed running with --tests when I did the rest of these.
> Elide unneeded lifetimes in tests

- lalrpop/src/lib.rs
This shows on the homepage of lib.rs, and is currently blank.  The README contains lots of good information and points users at the various documentation sources, so make it more visible to people checking out the crate on docs.rs.
While we're at it, warn about missing docs (which would have caught this omission).
> Use our README as a top level docstring

- lalrpop-test/src/lib.rs
The previous code typically takes several minutes of runtime to fail the verify_lalrpop_generates_itself test if that test fails.  The reason for this is that it is generating a diff output between the source controlled and the generated lrgrammar.rs using the diff library (https://docs.rs/diff/latest/diff/).  The diff library computes a diff using the LCS algorithm, which has a time complexity of O(m*n) (https://rajrajhans.com/2020/11/a-closer-look-at-diff-algorithms/).
Sometimes the diff time will be faster, because the diff library calculates a leading equality portion and a trailing equality portion and discards these before doing LCS on the middle
(https://github.com/utkarshkukreti/diff.rs/blob/4f5fac9898c54abdd59cad5d95dd615e685748d6/src/lib.rs#L53), however since many changes to …
> Fail more quickly when lalrpop does not generate itself

- lalrpop-util/src/lib.rs
> Fix a couple of typos

- lalrpop/src/normalize/prevalidate/mod.rs
I was looking a little into recursive_ascent/LALR support in LALRPOP and noticed the `#[test_all]` option. I believe this to be a superset code generation strategy that does both `#[recursive_ascent]` and `#[LALR]` and then compares the result.
I went and applied this annotation to all of the lalrpop_test grammars. This led to a funky error for the error_recovery_* grammars since it was skipping the validation check that just calling it with `#[recursive_ascent]` would have hit.
Unrelated, but I'm not sure yet why these are algorithm choices are set as annotations in the grammar. I'll have to do more research. I would have thought that this should be a configuration option that is independent from the lalrpop file.
> TestAll should also error when RecursiveAscent errors in validate

- lalrpop/src/lr1/build/test.rs
- lalrpop/src/lr1/codegen/ascent.rs
- lalrpop/src/lr1/codegen/base.rs
- lalrpop/src/lr1/codegen/parse_table.rs
- lalrpop/src/parser/lrgrammar.rs
This lint was moved by clippy into the pedantic group, so it's allowed by default anyways.
For the sake of users who may warn on it anyways, include it locally on the list of terminals where it's actually relevant.
In our own code base, just drop it, since the lint is allowed.
> Remove blanket allow(clippy::needless_raw_string_hashes)

- lalrpop/src/normalize/cond_comp/mod.rs
Recommended by clippy 1.84.  This is slightly more concise and readable, since it omits the extra argument.
> Convert map_or() to is_some_and()

- lalrpop/src/lr1/codegen/ascent.rs
- lalrpop/src/lr1/codegen/base.rs
- lalrpop/src/parser/lrgrammar.rs
Recursive ascent parsers sometimes generate loops that return once. Preventing this would needlessly complicate the code generation logic. Previously, we blanket-allowed never_loop because our recursive_ascent tests triggered clippy warnings on that.  Limit this allow to only the part of the code that actually needs it.
This will enable users to see this clippy lint on their action code where applicable.
> Isolate allow(clippy::never_loop) to the part of the code that needs it

- Cargo.lock
- doc/lexer/Cargo.toml
0.14.3 bumps msrv to 1.74, so our CI test for 1.70 build is currently
failing.
This can be removed once our MSRV moves to 1.74 or later.
> Pin lexer logos dependency to 0.14.2 for now

- lalrpop/src/build/mod.rs
- lalrpop/src/parser/lrgrammar.rs
The visibility Display impl will include a space (if needed - it may be the empty string).  Having an extra space in the trait declaration resulted in two spaces (or a line starting with a single space if the visibility displayed the empty string).
> Drop extra space in generated code

- lalrpop/src/generate.rs
> Replace `gen` keyword with `generator` instead of `r#gen`

- doc/src/SUMMARY.md
- doc/src/lexer_tutorial/006_error_recovery_custom_lexer.md
- doc/src/tutorial/008_error_recovery.md
Follow #992. I found a weird exit of parser when inputing an invalid token to trigger lexical error, where I expected error recovery should work. After discussing with @dburgener, we decide to address this issue temporarily in book. 
Since it's a minor change in user's code, I think it'll be unnecessary to provide an example code here. If needed, I have a copy of the example code on hand. Hope it could help.
> Add doc to handle lexical error in error recovery

- doc/src/advanced_setup.md
> Be more explicit about LALR deprecation in book

- .github/workflows/test.yaml
This reduces the risk of breakage when a dependency bumps msrv and is consistent with the guidance at https://doc.rust-lang.org/nightly/cargo/reference/rust-version.html
> Don't run cargo update on msrv or feature-powerset tests

- lalrpop/src/lr1/codegen/test_all.rs
The previous comment was copy/pasted from recursive ascent.  Update it to describe the purpose of the test all code generation strategy.
Reported by @glyh in #1008.
> Correct doc comment in test all

- lalrpop/Cargo.toml
- lalrpop/README.md
- lalrpop/src/lib.rs
When running cargo doc, the include_str command works fine, however, cargo publish relocates the package into target/package, so the relative path to the README is different, causing cargo publish to fail.
External discussion at:
https://github.com/rust-lang/cargo/issues/13309
https://users.rust-lang.org/t/include-str-does-not-work-when-releasing-because-of-changed-pathes/15551/14
The solution suggested in those links is to symlink the top level README inside your package, and then consistently refer to the README in the package.  That README will be copied into the right place during cargo publish.
> Cleanup README include in include_str

- .github/workflows/test.yaml
Try to catch publish issues in advance.
Cargo-release is not included in this PR because it has additional
pre-publish checks that I wasn't able to get working in CI.
> Dry run cargo publish in CI

- Cargo.lock
- doc/lexer/Cargo.toml
Now that our msrv is bumped to 1.81, the MSRV of logos is no longer a problem.
> Update logos to 0.15

- lalrpop-util/Cargo.toml
https://doc.rust-lang.org/cargo/reference/features.html#optional-dependencies
I recently learned that optional dependencies will be exposed as features unless the are explicitly marked as "dep:" for a another feature.  This means that lalrpop-util has a feature called "regex-automata" currently (see https://docs.rs/crate/lalrpop-util/0.22.0/features), which isn't what we want.  We want to have the dependency optionally when certain other features are enabled, but not expose it directly.
This is technically a breaking change
(https://doc.rust-lang.org/cargo/reference/semver.html#cargo-feature-remove). However, it would surprise me if any users use this feature.  In the interest of caution, it might make sense to hold this until we plan a breaking release anyways, since it's low priority.
> Specify optional regex_automata as "dep:".

- Cargo.lock
- lalrpop/Cargo.toml
- lalrpop/src/generate.rs
There is one breaking change that affects us.  gen_* functions have been deprecated in favor of new random_* functions, so update our usage of that.
> Update to rand 0.9

- doc/src/lexer_tutorial/006_error_recovery_custom_lexer.md
Fix #1038. Made it more clear to users that they need to also update the `extern` block in grammar for lexical error `Token::Error` from external lexer. Otherwise the error recovery may not work properly.
> Supplement section Error recovery with custom lexer in doc

- lalrpop/src/build/mod.rs
As noted in #1013, this PR aims to abstract error handling. The only file modified in this PR is `src/build/mod.rs`, where parse error reporting has been refactored out of the function `parse_and_normalize_grammar` into a new public function, `report_parse_error`.
The changes are straightforward: the new `report_parse_error` function is implemented in continuation-passing style, as it accepts a callback of type `impl FnMut(&FileText, pt::Span, &str, io::Error) -> E`. This design allows the caller to produce any desired error type.
That said, I wonder if error handling could be better organized. While this approach works well for all the use cases I've encountered, I suspect it’s far from optimal. Any feedback or suggestions would be greatly appreciated.
> Refactor `report_parse_error` in `crate::build`

- lalrpop/src/lr1/codegen/mod.rs
This new lint checks if we use format args in string literals that aren't passed to function that handle them like println!().  This makes sense normally, but in code generation contexts, we may be generating code like `rust!(rust, "println!("some format arg {}", arg))` which is a false positive hit for this lint.  There is only one such lint right now, but just blanket silence it in codegen and leave it on for the rest of the codebase, because it doesn't make sense in code generation.
> Silence new clippy lint literal_string_with_formatting_args in codegen

- lalrpop/src/build/mod.rs
- lalrpop/src/tok/mod.rs
- lalrpop/src/tok/test.rs
This PR adds support for the `\0` and `\x##` escape sequences in standard string literals. Use the format described by the Rust reference (https://doc.rust-lang.org/stable/reference/tokens.html#character-literals); disallowing 8-bit characters and truncated escape sequences.
Supporting the `\x` escape code allows matching terminals that contain nonprintable ASCII characters without resorting to a regex string.
> Support ASCII escape codes in string literals

- lalrpop/src/tok/mod.rs
Just suggesting to remove an unnecessary clone I noticed in #1047 by deriving copy on `Error`/`ErrorCode`.
(Waiting on #1047 first)
> Tok error copy

- .github/workflows/test.yaml
> Run checks on PRs to 0.22.x

- .github/workflows/test.yaml
This avoids the failure where lalrpop-util isn't actually uploaded (because of dry-run) when we try dry-running lalrpop.
> Run a workspace based dry-run

- lalrpop-test/src/lib.rs
- lalrpop-test/src/non_hash_user_error.lalrpop
Mentioned in #1052. I have tried to write out my rational at the top of the test grammar file.
> regression test for non_hash ParseError::User

- .github/workflows/test.yaml
- lalrpop-test/src/lib.rs
Adding a windows runner took a few more attempts than I would have expected. This change adds the os as part of the matrix of choices for the build job, using both ubuntu-latest and windows-latest. Generally, we can probably keep the rest of the workflows defaulting to ubuntu-latest
> Windows workflow in github actions

- lalrpop/src/api/mod.rs
- lalrpop/src/api/test.rs
- lalrpop/src/api/test_files/other/other.lalrpop
- lalrpop/src/api/test_files/outer.lalrpop
- lalrpop/src/api/test_files/src/src.lalrpop
- lalrpop/src/build/mod.rs
The prior code has weird corner cases around the difference between in_dir and the path passed to process_dir().  In many cases, they are the same, but sometimes they are not.  When they are not, the only behavior of in_dir is to effect where *output* files are placed, which is weird.  Depending on the various function calls, sometimes in_dir sets the path to search, but sometimes not, without rhyme or reason.
This commit changes in_dir to set the path to search if process() is called specifically.  Other process_*() family functions have a built in path to search, in which case in_dir is illegal.
Changing the output path based on the setting of in_dir is confusing and unexpected for users.  Drop that.  That seems to have originally been maintained for backwards compatibility.  The result …
> Stop using in_dir once we get to process_* family functions

- doc/calculator/src/calculator2b.lalrpop
- doc/lexer-modes/src/grammar.lalrpop
- lalrpop-test/src/error_recovery.lalrpop
- lalrpop-test/src/error_recovery_span.lalrpop
- lalrpop-test/src/where_clause_with_forall.lalrpop
- lalrpop/src/lr1/codegen/parse_table.rs
- lalrpop/src/normalize/norm_util.rs
- lalrpop/src/parser/lrgrammar.rs
> Fix uninlined format strings in generated code

- lalrpop-test/src/lib.rs
- lalrpop-test/src/loc_clone.lalrpop
- lalrpop-test/src/loc_clone_issue1064.rs
- lalrpop/src/lr1/codegen/ascent.rs
- lalrpop/src/lr1/codegen/base.rs
- lalrpop/src/lr1/codegen/parse_table.rs
- lalrpop/src/parser/lrgrammar.rs
After viewing the Issue #1064, it mentions that the MyLoc only implements Clone not Copy trait and suggests that `.clone()` should be added.  I added tests (see `lalrpop-test/src/loc_clone_issue1064.rs` and `lalrpop-test/src/loc_clone.lalrpop`) and made changes in `lalrpop/src/lr1/codegen/ascent.rs` and `lalrpop/src/lr1/codegen/parse_table.rs`. By applying these changes, I assume the `.clone()` issue might be solved.
> Fixes: Enforcing Clone in parser for custom Location

- Cargo.lock
- Cargo.toml
- RELEASES.md
- doc/calculator/Cargo.toml
- doc/cfg/Cargo.toml
- doc/lexer-modes/Cargo.toml
- doc/lexer/Cargo.toml
- doc/nobol/Cargo.toml
- doc/pascal/lalrpop/Cargo.toml
- doc/src/quick_start_guide.md
- doc/src/tutorial/001_adding_lalrpop.md
- doc/whitespace/Cargo.toml
- lalrpop/Cargo.toml
- lalrpop/src/parser/lrgrammar.rs
One note is that this also brings forward the version numbers across the board to 0.22.2 instead of 0.22.1.  I think that's fine, since 0.22.2 is a strict subset of master right now.  Just highlighting it, since it's a little weird given that 0.22.2 exists on the 0.22.x branch, but not the master branch.
> Forward port 0.22.2 release notes to main branch

- doc/src/tutorial/003_type_inference.md
- lalrpop-test/src/error_recovery_span.lalrpop
- lalrpop-test/src/inline.lalrpop
- lalrpop-test/src/match_alternatives.lalrpop
- lalrpop-test/src/match_section.lalrpop
- lalrpop-test/src/match_section_byte.lalrpop
- lalrpop/src/lr1/codegen/parse_table.rs
- lalrpop/src/normalize/lower/mod.rs
- lalrpop/src/parser/lrgrammar.rs
I had an idea for implementing multiple format arguments situational-ly choosing to expand `<>` to just `a` or `b`when the number of occurances of `<>` matches the number of anonymous variables. Currently we just expand `<>` to `a, b`.
There is a little more discussion I added in https://github.com/lalrpop/lalrpop/pull/1058 in relation to an alternative variation. We can treat `<>` situational-ly as a tuple of anonymous variables when we detect that the variables are not suppose to correspond to a struct creation.
We should think about which would be less-surprising to users. We could also consider changing the syntax in some way to make the positional part of this more explicit. Like `<Expr> "+" <Expr1> => format!("{<0>} + {<1>}"),` but I haven't investigated such other alternatives yet. …
> Multiple format arguments

- lalrpop/src/normalize/lower/mod.rs
The previous variable name really only refered to the first field of the tuple.  As a recent commit started using the second field of the tuple, this has become confusing.  Name the variable to be more clear.
> Make variable name clearer with anon symbols

- doc/src/lexer_tutorial/004_token_references.md
- doc/src/lexer_tutorial/005_external_lib.md
Blocks mislabeled as rust code could cause user confusion.
> Correctly label lalrpop code blocks in the lexer tutorial

- doc/src/lexer_tutorial/003_writing_custom_lexer.md
This caught me off-guard, and I would have preferred knowing about it ahead of time so I could design my `Location` type accordingly. So, add a note.
> Note the traits that custom lexer locations must implement
