- lalrpop/src/build/mod.rs
Fixes #45, but I'm not sure if this is the best approach
> Start processing at the current working directory

- README.md
- lalrpop-exe/Cargo.toml
- lalrpop-exe/src/main.rs
- lalrpop/Cargo.toml
- lalrpop/src/build/mod.rs
- lalrpop/src/lib.rs
- lalrpop/src/log.rs
- lalrpop/src/lr1/core/mod.rs
- lalrpop/src/lr1/core/test.rs
- lalrpop/src/lr1/la0/mod.rs
- lalrpop/src/lr1/la0/test.rs
- lalrpop/src/lr1/mod.rs
- lalrpop/src/normalize/inline/graph/test.rs
- lalrpop/src/normalize/inline/test.rs
- lalrpop/src/normalize/mod.rs
- lalrpop/src/session.rs
- publish.sh
Sometimes I want to run LALRPOP manually. And I'm amazed I got by this far without any logs. This also gives some simple profile information.
> Add logging and an independent LALRPOP executable.

- RELEASES.md
- lalrpop-test/src/error.rs
- lalrpop-test/src/expr.rs
- lalrpop-test/src/expr_arena.rs
- lalrpop-test/src/expr_generic.rs
- lalrpop-test/src/expr_intern_tok.rs
- lalrpop-test/src/expr_lalr.rs
- lalrpop-test/src/inline.rs
- lalrpop-test/src/intern_tok.rs
- lalrpop-test/src/lifetime_tok.rs
- lalrpop-test/src/loc.rs
- lalrpop-test/src/sub.rs
- lalrpop-test/src/use_super.rs
- lalrpop/src/build/fake_term.rs
- lalrpop/src/build/mod.rs
- lalrpop/src/lr1/ascent.rs
- lalrpop/src/lr1/build/test.rs
- lalrpop/src/lr1/build_lalr/test.rs
- lalrpop/src/lr1/error/test.rs
- lalrpop/src/main.rs
- lalrpop/src/message/test.rs
- lalrpop/src/rust/mod.rs
- lalrpop/src/session.rs
Fixes #57 
Also a few other minor things.
> Buffer output and only write to .rs file if successful

- README.md
- RELEASES.md
- doc/calculator/Cargo.toml
- doc/tutorial.md
- lalrpop/src/lr1/error/mod.rs
- lalrpop/src/lr1/error/test.rs
- lalrpop/src/lr1/lookahead.rs
- publish.sh
Some cases I wanted to work were not working.
> Improve the suggestions for inlining

- lalrpop-test/build.rs
- lalrpop-test/src/error.rs
- lalrpop-test/src/expr.rs
- lalrpop-test/src/expr_arena.rs
- lalrpop-test/src/expr_generic.rs
- lalrpop-test/src/expr_intern_tok.rs
- lalrpop-test/src/expr_lalr.rs
- lalrpop-test/src/inline.rs
- lalrpop-test/src/intern_tok.rs
- lalrpop-test/src/lifetime_tok.rs
- lalrpop-test/src/loc.rs
- lalrpop-test/src/loc_issue_90.rs
- lalrpop-test/src/sub.rs
- lalrpop-test/src/use_super.rs
- lalrpop/src/api/mod.rs
- lalrpop/src/build/mod.rs
- lalrpop/src/lexer/dfa/overlap.rs
- lalrpop/src/lib.rs
- lalrpop/src/lr1/ascent.rs
- lalrpop/src/main.rs
- lalrpop/src/session.rs
Configuration builder should let us grow the API in a backwards compatible way.
Also, fix docopt handling for `--help`.
Fixes #99.
> Introduce a `Configuration` builder for advanced usage

- lalrpop/src/main.rs
Fix regression introduced by d70cfac7.
> Fix bug in USAGE and add regression tests.

- doc/calculator/src/calculator3.lalrpop
- doc/tutorial.md
am going through tutorial and thought this might be a nice improvement. really enjoying the project so far!
> fix spacing and add trailing commas to calc3 example

- lalrpop/src/lexer/nfa/mod.rs
- lalrpop/src/lexer/nfa/test.rs
We are supposed to push all edges from a given node together.
Fixes #101
> push "alternate" edges in one swoop

- doc/lexer_tutorial.md
- doc/whitespace/Cargo.toml
- doc/whitespace/build.rs
- doc/whitespace/hello. 
- doc/whitespace/src/ast.rs
- doc/whitespace/src/lexer.rs
- doc/whitespace/src/lib.rs
- doc/whitespace/src/main.rs
- doc/whitespace/src/parser.lalrpop
Partly addresses #39. I implemented a Whitespace parser to demonstrate custom lexers.
> Rough draft of lexer tutorial

- lalrpop/src/collections/multimap.rs
- lalrpop/src/lr1/build/mod.rs
- lalrpop/src/lr1/build/test.rs
- lalrpop/src/lr1/first/mod.rs
- lalrpop/src/lr1/first/test.rs
- lalrpop/src/lr1/lookahead.rs
> Compute transitive closure correctly

- lalrpop/src/lr1/codegen/parse_table.rs
- lalrpop/src/rust/mod.rs
This commit avoids writing a description of each terminal as a comment if comments are disabled. It also writes all terminals for a state on a single line which effectively reduces the size of tables from `O(terminals * states)` to `O(states)` (if comments are disabled).
cc #65, #164
> fix: Shrink the amount of lines written for parse tables

- README.md
- doc/calculator/Cargo.toml
- doc/whitespace/Cargo.toml
- publish.sh
cargo test --all can be eventually used for
the whole workspace testing after all doctests
pass.
> unify dep info

- lalrpop/src/build/mod.rs
- lalrpop/src/tok/mod.rs
- lalrpop/src/tok/test.rs
Tokenizer handles rust's character literals in a similar way to string literals.
> Issue157 bracket chars are perceived as part of syntax

- lalrpop/src/lr1/build/mod.rs
Solution for nikomatsakis/lalrpop#203
The lane-table-method is used when environment variable `LALRPOP_LANE_TABLE` is set to `enabled`.
> Enabling lane-table-algorithm via environment variable

- .gitignore
- doc/calculator/src/calculator2b.lalrpop
- doc/calculator/src/main.rs
- doc/tutorial.md
- lalrpop-test/src/match_section.rs
> extend the tutorial to explain lexing vs parsing

- lalrpop-test/src/expr_module_attributes.lalrpop
- lalrpop-test/src/main.rs
- lalrpop/src/build/mod.rs
- lalrpop/src/grammar/parse_tree.rs
- lalrpop/src/grammar/repr.rs
- lalrpop/src/normalize/lower/mod.rs
- lalrpop/src/parser/lrgrammar.lalrpop
- lalrpop/src/rust/mod.rs
- lalrpop/src/tok/mod.rs
- lalrpop/src/tok/test.rs
> Issue115 allow shebang in lalrpop files

- lalrpop/src/main.rs
this solves https://github.com/nikomatsakis/lalrpop/issues/224
> Added version information for lalrpop executable

- lalrpop/src/build/mod.rs
> Embed LALRPOP version in generated files, and check it on rebuild

- .gitignore
- lalrpop-test/src/main.rs
- lalrpop-test/src/partial_parse.lalrpop
- lalrpop/src/lr1/codegen/parse_table.rs
- lalrpop/src/lr1/lane_table/construct/mod.rs
Fixes #253.
Also includes a *possible* fix for #240 -- but I need to validate that.
> error out with extra tokens, even in parse table mode

- lalrpop-test/src/associated_types.lalrpop
- lalrpop-test/src/associated_types.rs
- lalrpop-test/src/associated_types_lib.rs
- lalrpop-test/src/main.rs
- lalrpop/src/grammar/parse_tree.rs
- lalrpop/src/grammar/repr.rs
- lalrpop/src/lr1/codegen/ascent.rs
- lalrpop/src/lr1/codegen/parse_table.rs
- lalrpop/src/normalize/tyinfer/mod.rs
> Allow actions to return a grammar's type parameter's associated type

- lalrpop-snap/Cargo.toml
- lalrpop/Cargo.toml
https://crates.io/categories/parsing
> Crates to help create parsers of binary and text formats.
> Specify `parsing` category in Cargo.toml

- doc/tutorial.md
> Add missing comma in tutorial

- doc/tutorial.md
> Add example with funky expression and tupels

- README.md
- doc/tutorial.md
these were missed in df38c3e2aede76c218786cb7574babd5608e3d5b
> update version strings in README.md and doc/tutorial.md to 0.14.0

- lalrpop/src/normalize/prevalidate/mod.rs
- lalrpop/src/normalize/prevalidate/test.rs
> Add error when macros are marked public.

- lalrpop/src/lib.rs
> Remove unused re-export.

- publish.sh
> Add support for git tags when publishing.

- doc/src/tutorial/003_type_inference.md
Just a small fix - the lifetime should have been `'input`, not `'static`.
> Correct a typo in the tutorial.

- lalrpop/src/lexer/intern_token/mod.rs
- lalrpop/src/lr1/codegen/base.rs
> Add MatcherBuilder, which stores regexes across multiple parses.

- doc/calculator/src/main.rs
- doc/pascal/lalrpop/src/main.rs
- doc/whitespace/src/lib.rs
- lalrpop-test/src/lib.rs
- lalrpop-test/src/loc_issue_90_lib.rs
- lalrpop/src/build/action.rs
- lalrpop/src/build/mod.rs
- lalrpop/src/lr1/codegen/ascent.rs
- lalrpop/src/lr1/codegen/base.rs
- lalrpop/src/lr1/codegen/parse_table.rs
- lalrpop/src/lr1/codegen/test_all.rs
- lalrpop/src/rust/mod.rs
> Change parse_X to XParser::parse.

- lalrpop/src/lr1/codegen/base.rs
- lalrpop/src/lr1/codegen/test_all.rs
> Store the MatcherBuilder in the Parser.

- README.md
Might be handy for people new to LALRPOP, who'd want to jump straight in.
> Add real-life examples to README

- doc/src/tutorial/001_adding_lalrpop.md
- version.sh
See https://github.com/lalrpop/lalrpop/pull/346#issuecomment-375585781
> Update the version of the tutorial examples as well

- lalrpop-test/src/issue_394.lalrpop
- lalrpop-test/src/lib.rs
- lalrpop/src/lr1/codegen/parse_table.rs
>  fix: Don't generate reduce actions which do not fit in the integer size 

- lalrpop/src/lexer/intern_token/mod.rs
> Allow trim_left in the generated code

- README.md
> Add gleam to example uses

- README.md
It's surprisingly hard to google it when you don't  know about it at all.
> Add a link to gitter lobby

- RELEASES.md
> Add link for issues

- doc/src/lexer_tutorial/001_lexer_gen.md
- doc/src/quick_start_guide.md
- doc/src/tutorial/001_adding_lalrpop.md
- doc/src/tutorial/002_paren_numbers.md
- doc/src/tutorial/003_type_inference.md
- doc/src/tutorial/004_full_expressions.md
- doc/src/tutorial/005_building_asts.md
- doc/src/tutorial/006_macros.md
- doc/src/tutorial/index.md
Fixed invalid links and extensions
> Fix tutorial document link

- doc/src/quick_start_guide.md
- doc/src/tutorial/001_adding_lalrpop.md
- lalrpop/Cargo.toml
These changes aim to help out people like me that are new to the project and new-ish to Rust. I hope they seem like reasonable changes. They should also help with #538.
> Small documentation improvements for beginners

- lalrpop/src/build/mod.rs
- lalrpop/src/lr1/codegen/ascent.rs
- lalrpop/src/lr1/codegen/parse_table.rs
> fix visibility of internal types

- lalrpop/src/normalize/macro_expand/test.rs
- lalrpop/src/normalize/tyinfer/test.rs
- lalrpop/src/parser/lrgrammar.rs
- lalrpop/src/test_util.rs
Probably fallout from: 49bd3dc: fix more no-std items
> Fix various test failures.

- doc/calculator/src/main.rs
- lalrpop-test/src/lib.rs
- lalrpop-test/src/util/tok.rs
There are compilation warnings in various bits and pieces, under Rust 1.50.
> Fix warnings

- tools/ci-install.sh
> Update mdbook version

- doc/src/tutorial/008_error_recovery.md
> Fixed typo

- lalrpop/src/lr1/codegen/parse_table.rs
- lalrpop/src/normalize/mod.rs
Corrected the code that is considered as an error in a future version, eliminating some warnings.
> Eliminate warnings.

- lalrpop/src/lr1/lane_table/construct/merge.rs
- lalrpop/src/lr1/lane_table/test.rs
> Update the state index when splitting a state

- doc/src/tutorial/008_error_recovery.md
* Add code example of use declaration
* Add link to calculator7 example
* Explain what ErrorRecovery struct does
* Fix typo
> Clarify error recovery documentation

- doc/src/SUMMARY.md
- doc/src/lexer_tutorial/004_external_lib.md
- doc/src/lexer_tutorial/index.md
Hello,
First of all, thanks for the awesome library, I've started to use it to implement my own programming language [Letlang](https://letlang.dev).
I've been using [Logos](https://docs.rs/logos/latest/logos/) to implement a custom Lexer, and both libraries work so well together.
This is why I thought it would be great to have a tutorial in the documentation exploring this idea.
I'll be available all weekend to implement potential request changes, or during the week after 6PM in the Europe/Paris timezone.
Hope you'll like it 🙂
> Add Lexer tutorial for Logos

- doc/src/lexer_tutorial/001_lexer_gen.md
Just fixing what i believe to be a typo.
> fix: small typo

- doc/calculator/Cargo.toml
- doc/pascal/lalrpop/Cargo.toml
- doc/whitespace/Cargo.toml
- doc/whitespace/src/parser.lalrpop
- lalrpop-test/src/lib.rs
- lalrpop-util/src/lib.rs
- lalrpop/src/parser/lrgrammar.lalrpop
- lalrpop/src/parser/lrgrammar.rs
Hello hello
I've hit https://github.com/lalrpop/lalrpop/issues/616 with a toy project of mine and wasn't able to easily use any workarounds.
I came across https://github.com/lalrpop/lalrpop/issues/515 and done my best to implement a first step -- using 2018 across the whole repo.
Assuming all looks good here I intend to implement next steps for 2021 as well.
(I've followed https://github.com/lalrpop/lalrpop/blob/master/CONTRIBUTING.md but apologies if I missed something)
> Update to 2018 edition

- lalrpop/src/lr1/interpret.rs
- lalrpop/src/lr1/mod.rs
- lalrpop/src/lr1/report/mod.rs
- lalrpop/src/lr1/trace/reduce/test.rs
- lalrpop/src/lr1/trace/shift/test.rs
- lalrpop/src/lr1/trace/trace_graph/test.rs
- lalrpop/src/message/test.rs
- lalrpop/src/parser/mod.rs
- lalrpop/src/test_util.rs
another trivial clippy fix seperation from #743 
by @DaniPopes
> chore: clippy

- lalrpop/src/main.rs
- lalrpop/src/parser/lrgrammar.rs
As mentioned in https://github.com/lalrpop/lalrpop/pull/752, the CI wasn't correctly propagating up failures, so "cargo test" has been failing in CI recently, despite a green checkmark.
> Fix test failures

- .github/workflows/test.yaml
> Add 1.60.0 to CI as (temporary) MSRV

- .github/workflows/test.yaml
part of #742
split from #763 to unblock other patches quickly
> Remove 1.60.0 from CI

- .github/workflows/test.yaml
- lalrpop/src/normalize/precedence/mod.rs
- lalrpop/src/session.rs
by @DaniPopes split from #743
Need decision from #742
> Use #[default] for enum default

- RELEASES.md
To make 0.20 notes on the top of it.
> Copy release note from 0.19.12

- lalrpop/src/main.rs
- lalrpop/src/rust/mod.rs
- lalrpop/src/tls/mod.rs
- tools/build-doc
- tools/ci.sh
> Improve RustWrite by @DaniPopes

- lalrpop-test/src/lib.rs
- lalrpop-test/src/user_defined_error_crate_public.lalrpop
- lalrpop-test/src/user_defined_error_private.lalrpop
- lalrpop-test/src/user_defined_error_public.lalrpop
- lalrpop-test/src/user_defined_error_visibility.rs
- lalrpop/src/build/mod.rs
- lalrpop/src/lr1/codegen/ascent.rs
- lalrpop/src/lr1/codegen/parse_table.rs
- lalrpop/src/parser/lrgrammar.rs
This reduces the visibility of various items internal to LALRPOP, with the goal of allowing a non-public custom error type.
I believe this also fixes #519.
> User error visibility

- README.md
> Document the cheat sheet in the README

- lalrpop/src/lr1/trace/trace_graph/test.rs
- lalrpop/src/normalize/prevalidate/mod.rs
> Clippy1.77 lints

- doc/nobol/src/main.rs
- doc/src/lexer_tutorial/002_raw_delimited_content.md
- lalrpop/src/lexer/nfa/mod.rs
- lalrpop/src/lr1/trace/trace_graph/mod.rs
> Fix some typos

- lalrpop/src/lr1/codegen/base.rs
- lalrpop/src/lr1/lane_table/construct/mod.rs
- lalrpop/src/lr1/mod.rs
- lalrpop/src/parser/lrgrammar.rs
> Fix latest clippy findings

- lalrpop/src/build/action.rs
- lalrpop/src/lexer/nfa/mod.rs
- lalrpop/src/lr1/codegen/parse_table.rs
> Fix clippy issues for rust 1.81

- doc/src/SUMMARY.md
- doc/src/location_tracking.md
- doc/src/tutorial/index.md
> Add a section on location tracking macros to the book

- doc/src/tutorial/001_adding_lalrpop.md
> Add attributes in lalrpop_mod to tutorial

- lalrpop/src/build/mod.rs
This lets users who want to proceed even on lalrpop failure do so.  The common case of calling .unwrap() on lalrpop's return will continue to exit at (roughly the same place), seeing a panic rather than an exit, which is probably more in line with expected behavior.
The approach in this commit is the least invasive way to achieve this goal, since the existing returns are io::Result, this commit just returns an io::Error (mostly ErrorKind::InvalidData) on various lalrpop failures.  An alternative approach would be to define a lalrpop error type and return that.  The existing lalrpop_util::ParseError covers some but not all of the relevant cases, since it only covers errors at the parse stage, not later stages of compilation.  I'm not sure the effort to fully propagate all the errors up is …
> Don't call exit() in a library, instead return an error to the user

- lalrpop/src/lr1/error/mod.rs
- lalrpop/src/lr1/error/test.rs
conflict, supress the naive ones.
When reporting an error, conflict resolution creates error states for the all the terminals in the grammar, which can be a lot of errors. Some of these will hopefully classify as the more helpful error messages, but for terminals that can't shift to a valid production, lalrpop won't be able to produce a good error message.  This can result in error messages that have many naive errors burying the more helpful ones.
Check what sorts of errors we will be displaying before displaying them. If all we got is naive errors, just display those.  If we got some good errors, use those instead and discard the naive errors.
> If there are both naive and better errors available for a given

- doc/cfg/Cargo.toml
- doc/cfg/src/cfg.lalrpop
- doc/cfg/src/lib.rs
> Add a test-set2 to properly test all features construct

- CONTRIBUTING.md
> Mention the clog-cli prereq in the CONTRIBUTING release process

- doc/src/cheatsheet.md
> update cheatsheet pointer for positions

- doc/lexer-modes/src/lib.rs
- doc/lexer-modes/src/test.rs
- doc/lexer/src/lib.rs
- doc/lexer/src/test.rs
- lalrpop/src/lr1/report/mod.rs
- lalrpop/src/lr1/report/test.rs
> Add some extra tests for untested areas of the codebase.

- CONTRIBUTING.md
It took a little while to get this working, so I wanted to make sure it's documented for future me or anyone else who may attempt it.
> Add code coverage write-up to contributing doc

- .github/workflows/test.yaml
- Cargo.lock
- Cargo.toml
- RELEASES.md
- doc/calculator/Cargo.toml
- doc/calculator/src/calculator2b.lalrpop
- doc/cfg/Cargo.toml
- doc/lexer-modes/Cargo.toml
- doc/lexer-modes/src/grammar.lalrpop
- doc/lexer/Cargo.toml
- doc/nobol/Cargo.toml
- doc/pascal/lalrpop/Cargo.toml
- doc/src/lexer_tutorial/006_error_recovery_custom_lexer.md
- doc/src/quick_start_guide.md
- doc/src/tutorial/001_adding_lalrpop.md
- doc/whitespace/Cargo.toml
- lalrpop-test/src/error_recovery.lalrpop
- lalrpop-test/src/error_recovery_span.lalrpop
- lalrpop-test/src/where_clause_with_forall.lalrpop
- lalrpop/Cargo.toml
- lalrpop/src/build/mod.rs
- lalrpop/src/lr1/codegen/parse_table.rs
- lalrpop/src/normalize/norm_util.rs
- lalrpop/src/parser/lrgrammar.rs
- lalrpop/src/tok/mod.rs
- lalrpop/src/tok/test.rs
> 0.22.2 backports
